LogTo("C:/Users/jeffr/Downloads/Lifting/compare_h_cache_strategies_s12.log");
Print("=== TRADITIONAL vs S3-ONLY h_cache, 20 random S12 combos ===\n");

Q_C2 := CyclicGroup(IsPermGroup, 2);
Q_C3 := CyclicGroup(IsPermGroup, 3);
Q_S3 := SymmetricGroup(3);
Q_GROUPS := [Q_C2, Q_C3, Q_S3];

ConjAction := function(K, g) return K^g; end;
SafeId := function(G)
    local n;
    n := Size(G);
    if IdGroupsAvailable(n) then return [n, 0, IdGroup(G)]; fi;
    return [n, 1, AbelianInvariants(G), List(DerivedSeries(G), Size)];
end;

_IndexPNormals := function(H, p)
    local DH, hom, A, max_subs;
    DH := DerivedSubgroup(H);
    if Index(H, DH) mod p <> 0 then return []; fi;
    hom := NaturalHomomorphismByNormalSubgroup(H, DH);
    A := Range(hom);
    max_subs := Filtered(MaximalSubgroupClassReps(A), K -> Index(A, K) = p);
    return List(max_subs, K -> PreImage(hom, K));
end;

_TieredEnumerate := function(H, q_groups)
    local result, Q, sz, kers;
    result := [];
    for Q in q_groups do
        sz := Size(Q);
        if IsPrimeInt(sz) then
            Append(result, _IndexPNormals(H, sz));
        else
            Append(result, Set(List(GQuotients(H, Q), Kernel)));
        fi;
    od;
    return Set(result);
end;

_OrbitRecs := function(H, N_H, normals)
    local K_orbit, K_H, hom_H, Q_H, Stab_NH_KH, orbits;
    orbits := [];
    for K_orbit in Orbits(N_H, normals, ConjAction) do
        K_H := K_orbit[1];
        hom_H := NaturalHomomorphismByNormalSubgroup(H, K_H);
        Q_H := Range(hom_H);
        Stab_NH_KH := Stabilizer(N_H, K_H, ConjAction);
        Add(orbits, rec(qsize := Size(Q_H), qid := SafeId(Q_H)));
    od;
    return orbits;
end;

TimeOneH := function(H, S_M)
    local trad_t, trad_normals, trad_orbits, trad_total, new_t,
          new_normals, new_orbits, new_total, norm_t, N_W;
    norm_t := Runtime();
    N_W := Normalizer(S_M, H);
    norm_t := Runtime() - norm_t;
    # Traditional: NormalSubgroups(H) + filter (none here, take all) + orbit-decomp
    trad_t := Runtime();
    trad_normals := Filtered(NormalSubgroups(H), K -> K <> H);
    trad_t := Runtime() - trad_t;
    trad_orbits := Runtime();
    trad_orbits := _OrbitRecs(H, N_W, trad_normals);
    trad_total := norm_t + trad_t + (Runtime() - trad_t - norm_t);
    # S3-only: tiered enum + orbit-decomp on filtered list
    new_t := Runtime();
    new_normals := _TieredEnumerate(H, Q_GROUPS);
    new_t := Runtime() - new_t;
    new_orbits := Runtime();
    new_orbits := _OrbitRecs(H, N_W, new_normals);
    new_total := norm_t + new_t + (Runtime() - new_t - norm_t);
    return rec(
        norm_ms := norm_t,
        trad_enum_ms := trad_t,
        trad_normals := Length(trad_normals),
        trad_orbits := Length(trad_orbits),
        new_enum_ms := new_t,
        new_normals := Length(new_normals),
        new_orbits := Length(new_orbits)
    );
end;

agg_norm := 0;
agg_trad_enum := 0;
agg_trad_norms := 0;
agg_trad_orbits := 0;
agg_new_enum := 0;
agg_new_norms := 0;
agg_new_orbits := 0;
agg_h := 0;

Print("\n=== [12]/[12,106] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
combo_norm := 0; combo_trad_e := 0; combo_trad_n := 0; combo_trad_o := 0;
combo_new_e := 0; combo_new_n := 0; combo_new_o := 0;
H := Group([(1,12)(2,3),(1,12)(4,5),(1,12)(6,7),(1,5,9)(2,6,10)(3,7,11)(4,8,12),(1,11)(2,8)(3,9)(4,6)(5,7)(10,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
Print("  norm=", combo_norm, "ms  trad_enum=", combo_trad_e,"ms (",combo_trad_n," normals, ", combo_trad_o, " orbits)  new_enum=", combo_new_e, "ms (", combo_new_n, " normals, ",combo_new_o, " orbits)\n");
agg_norm := agg_norm + combo_norm;
agg_trad_enum := agg_trad_enum + combo_trad_e;
agg_trad_norms := agg_trad_norms + combo_trad_n;
agg_trad_orbits := agg_trad_orbits + combo_trad_o;
agg_new_enum := agg_new_enum + combo_new_e;
agg_new_norms := agg_new_norms + combo_new_n;
agg_new_orbits := agg_new_orbits + combo_new_o;

Print("\n=== [12]/[12,109] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
combo_norm := 0; combo_trad_e := 0; combo_trad_n := 0; combo_trad_o := 0;
combo_new_e := 0; combo_new_n := 0; combo_new_o := 0;
H := Group([(1,12)(4,5),(1,12)(8,9),(1,3,5,7,9,11)(2,4,6,8,10,12),(1,11)(2,8)(3,9)(4,6)(5,7)(10,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
Print("  norm=", combo_norm, "ms  trad_enum=", combo_trad_e,"ms (",combo_trad_n," normals, ", combo_trad_o, " orbits)  new_enum=", combo_new_e, "ms (", combo_new_n, " normals, ",combo_new_o, " orbits)\n");
agg_norm := agg_norm + combo_norm;
agg_trad_enum := agg_trad_enum + combo_trad_e;
agg_trad_norms := agg_trad_norms + combo_trad_n;
agg_trad_orbits := agg_trad_orbits + combo_trad_o;
agg_new_enum := agg_new_enum + combo_new_e;
agg_new_norms := agg_new_norms + combo_new_n;
agg_new_orbits := agg_new_orbits + combo_new_o;

Print("\n=== [12]/[12,115] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
combo_norm := 0; combo_trad_e := 0; combo_trad_n := 0; combo_trad_o := 0;
combo_new_e := 0; combo_new_n := 0; combo_new_o := 0;
H := Group([(1,12)(2,3)(6,7)(8,9),(1,12)(2,3)(4,5),(1,5,9)(2,6,10)(3,7,11)(4,8,12),(2,4)(3,5)(6,7)(8,10)(9,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
Print("  norm=", combo_norm, "ms  trad_enum=", combo_trad_e,"ms (",combo_trad_n," normals, ", combo_trad_o, " orbits)  new_enum=", combo_new_e, "ms (", combo_new_n, " normals, ",combo_new_o, " orbits)\n");
agg_norm := agg_norm + combo_norm;
agg_trad_enum := agg_trad_enum + combo_trad_e;
agg_trad_norms := agg_trad_norms + combo_trad_n;
agg_trad_orbits := agg_trad_orbits + combo_trad_o;
agg_new_enum := agg_new_enum + combo_new_e;
agg_new_norms := agg_new_norms + combo_new_n;
agg_new_orbits := agg_new_orbits + combo_new_o;

Print("\n=== [12]/[12,119] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
combo_norm := 0; combo_trad_e := 0; combo_trad_n := 0; combo_trad_o := 0;
combo_new_e := 0; combo_new_n := 0; combo_new_o := 0;
H := Group([(2,6,10)(3,7,11)(4,8,12),(1,5)(2,10)(4,8)(7,11),(1,4,7,10)(2,5,8,11)(3,6,9,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
Print("  norm=", combo_norm, "ms  trad_enum=", combo_trad_e,"ms (",combo_trad_n," normals, ", combo_trad_o, " orbits)  new_enum=", combo_new_e, "ms (", combo_new_n, " normals, ",combo_new_o, " orbits)\n");
agg_norm := agg_norm + combo_norm;
agg_trad_enum := agg_trad_enum + combo_trad_e;
agg_trad_norms := agg_trad_norms + combo_trad_n;
agg_trad_orbits := agg_trad_orbits + combo_trad_o;
agg_new_enum := agg_new_enum + combo_new_e;
agg_new_norms := agg_new_norms + combo_new_n;
agg_new_orbits := agg_new_orbits + combo_new_o;

Print("\n=== [12]/[12,220] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
combo_norm := 0; combo_trad_e := 0; combo_trad_n := 0; combo_trad_o := 0;
combo_new_e := 0; combo_new_n := 0; combo_new_o := 0;
H := Group([(1,3,5)(2,4,12)(7,9,11),(1,7,3,9,5)(2,4,6,8,10),(1,9)(2,12)(3,7)(5,11),(1,12)(2,3)(4,11)(5,10)(6,9)(7,8)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
Print("  norm=", combo_norm, "ms  trad_enum=", combo_trad_e,"ms (",combo_trad_n," normals, ", combo_trad_o, " orbits)  new_enum=", combo_new_e, "ms (", combo_new_n, " normals, ",combo_new_o, " orbits)\n");
agg_norm := agg_norm + combo_norm;
agg_trad_enum := agg_trad_enum + combo_trad_e;
agg_trad_norms := agg_trad_norms + combo_trad_n;
agg_trad_orbits := agg_trad_orbits + combo_trad_o;
agg_new_enum := agg_new_enum + combo_new_e;
agg_new_norms := agg_new_norms + combo_new_n;
agg_new_orbits := agg_new_orbits + combo_new_o;

Print("\n=== [12]/[12,232] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
combo_norm := 0; combo_trad_e := 0; combo_trad_n := 0; combo_trad_o := 0;
combo_new_e := 0; combo_new_n := 0; combo_new_o := 0;
H := Group([(4,8,12),(1,5)(2,10)(4,8)(7,11),(1,7,10)(2,5,11)(3,6,9),(2,8,7)(3,6,12)(4,11,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
Print("  norm=", combo_norm, "ms  trad_enum=", combo_trad_e,"ms (",combo_trad_n," normals, ", combo_trad_o, " orbits)  new_enum=", combo_new_e, "ms (", combo_new_n, " normals, ",combo_new_o, " orbits)\n");
agg_norm := agg_norm + combo_norm;
agg_trad_enum := agg_trad_enum + combo_trad_e;
agg_trad_norms := agg_trad_norms + combo_trad_n;
agg_trad_orbits := agg_trad_orbits + combo_trad_o;
agg_new_enum := agg_new_enum + combo_new_e;
agg_new_norms := agg_new_norms + combo_new_n;
agg_new_orbits := agg_new_orbits + combo_new_o;

Print("\n=== [12]/[12,249] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
combo_norm := 0; combo_trad_e := 0; combo_trad_n := 0; combo_trad_o := 0;
combo_new_e := 0; combo_new_n := 0; combo_new_o := 0;
H := Group([(4,8,12),(2,10)(4,8),(2,8,10,4)(6,12),(1,12)(2,3)(4,5)(6,7)(8,9)(10,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
Print("  norm=", combo_norm, "ms  trad_enum=", combo_trad_e,"ms (",combo_trad_n," normals, ", combo_trad_o, " orbits)  new_enum=", combo_new_e, "ms (", combo_new_n, " normals, ",combo_new_o, " orbits)\n");
agg_norm := agg_norm + combo_norm;
agg_trad_enum := agg_trad_enum + combo_trad_e;
agg_trad_norms := agg_trad_norms + combo_trad_n;
agg_trad_orbits := agg_trad_orbits + combo_trad_o;
agg_new_enum := agg_new_enum + combo_new_e;
agg_new_norms := agg_new_norms + combo_new_n;
agg_new_orbits := agg_new_orbits + combo_new_o;

Print("\n=== [12]/[12,266] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
combo_norm := 0; combo_trad_e := 0; combo_trad_n := 0; combo_trad_o := 0;
combo_new_e := 0; combo_new_n := 0; combo_new_o := 0;
H := Group([(4,8,12),(2,10)(4,8),(1,10)(2,5)(3,12)(4,7)(6,9)(8,11),(1,7)(2,8)(3,9)(4,10)(5,11)(6,12),(1,7,5,11)(2,10)(3,9)(4,8)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
Print("  norm=", combo_norm, "ms  trad_enum=", combo_trad_e,"ms (",combo_trad_n," normals, ", combo_trad_o, " orbits)  new_enum=", combo_new_e, "ms (", combo_new_n, " normals, ",combo_new_o, " orbits)\n");
agg_norm := agg_norm + combo_norm;
agg_trad_enum := agg_trad_enum + combo_trad_e;
agg_trad_norms := agg_trad_norms + combo_trad_n;
agg_trad_orbits := agg_trad_orbits + combo_trad_o;
agg_new_enum := agg_new_enum + combo_new_e;
agg_new_norms := agg_new_norms + combo_new_n;
agg_new_orbits := agg_new_orbits + combo_new_o;

Print("\n=== [12]/[12,45] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
combo_norm := 0; combo_trad_e := 0; combo_trad_n := 0; combo_trad_o := 0;
combo_new_e := 0; combo_new_n := 0; combo_new_o := 0;
H := Group([(1,4,7,10)(2,5,8,11)(3,6,9,12),(1,10)(2,5)(6,9),(1,5,9)(2,6,10)(3,7,11)(4,8,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
Print("  norm=", combo_norm, "ms  trad_enum=", combo_trad_e,"ms (",combo_trad_n," normals, ", combo_trad_o, " orbits)  new_enum=", combo_new_e, "ms (", combo_new_n, " normals, ",combo_new_o, " orbits)\n");
agg_norm := agg_norm + combo_norm;
agg_trad_enum := agg_trad_enum + combo_trad_e;
agg_trad_norms := agg_trad_norms + combo_trad_n;
agg_trad_orbits := agg_trad_orbits + combo_trad_o;
agg_new_enum := agg_new_enum + combo_new_e;
agg_new_norms := agg_new_norms + combo_new_n;
agg_new_orbits := agg_new_orbits + combo_new_o;

Print("\n=== [4,4,4]/[4,2]_[4,2]_[4,4] (M=12, 3 H) ===\n");
S_M := SymmetricGroup(12);
combo_norm := 0; combo_trad_e := 0; combo_trad_n := 0; combo_trad_o := 0;
combo_new_e := 0; combo_new_n := 0; combo_new_o := 0;
H := Group([(1,4)(2,3),(1,2)(3,4),(5,8)(6,7),(5,6)(7,8),(9,10,11),(10,11,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,4)(2,3),(1,2)(3,4)(5,6)(7,8),(5,8)(6,7),(9,10,11),(10,11,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,4)(2,3)(5,8)(6,7),(1,2)(3,4)(5,6)(7,8),(9,10,11),(10,11,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
Print("  norm=", combo_norm, "ms  trad_enum=", combo_trad_e,"ms (",combo_trad_n," normals, ", combo_trad_o, " orbits)  new_enum=", combo_new_e, "ms (", combo_new_n, " normals, ",combo_new_o, " orbits)\n");
agg_norm := agg_norm + combo_norm;
agg_trad_enum := agg_trad_enum + combo_trad_e;
agg_trad_norms := agg_trad_norms + combo_trad_n;
agg_trad_orbits := agg_trad_orbits + combo_trad_o;
agg_new_enum := agg_new_enum + combo_new_e;
agg_new_norms := agg_new_norms + combo_new_n;
agg_new_orbits := agg_new_orbits + combo_new_o;

Print("\n=== [5,4,3]/[3,1]_[4,3]_[5,3] (M=12, 4 H) ===\n");
S_M := SymmetricGroup(12);
combo_norm := 0; combo_trad_e := 0; combo_trad_n := 0; combo_trad_o := 0;
combo_new_e := 0; combo_new_n := 0; combo_new_o := 0;
H := Group([(1,2,3,4,5),(1,2,4,3),(6,7,8),(9,10,11,12),(9,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3,4,5),(1,2,4,3)(9,11),(6,7,8),(9,12,11,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3,4,5),(1,2,4,3)(9,10,11,12),(6,7,8),(9,11)(10,12),(9,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3,4,5),(1,2,4,3)(9,11),(6,7,8),(9,10)(11,12),(9,12)(10,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
Print("  norm=", combo_norm, "ms  trad_enum=", combo_trad_e,"ms (",combo_trad_n," normals, ", combo_trad_o, " orbits)  new_enum=", combo_new_e, "ms (", combo_new_n, " normals, ",combo_new_o, " orbits)\n");
agg_norm := agg_norm + combo_norm;
agg_trad_enum := agg_trad_enum + combo_trad_e;
agg_trad_norms := agg_trad_norms + combo_trad_n;
agg_trad_orbits := agg_trad_orbits + combo_trad_o;
agg_new_enum := agg_new_enum + combo_new_e;
agg_new_norms := agg_new_norms + combo_new_n;
agg_new_orbits := agg_new_orbits + combo_new_o;

Print("\n=== [5,4,3]/[3,1]_[4,5]_[5,3] (M=12, 2 H) ===\n");
S_M := SymmetricGroup(12);
combo_norm := 0; combo_trad_e := 0; combo_trad_n := 0; combo_trad_o := 0;
combo_new_e := 0; combo_new_n := 0; combo_new_o := 0;
H := Group([(1,2,3,4,5),(1,2,4,3),(6,7,8),(9,10,11,12),(9,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3,4,5),(1,2,4,3)(9,10),(6,7,8),(10,12,11),(9,12,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
Print("  norm=", combo_norm, "ms  trad_enum=", combo_trad_e,"ms (",combo_trad_n," normals, ", combo_trad_o, " orbits)  new_enum=", combo_new_e, "ms (", combo_new_n, " normals, ",combo_new_o, " orbits)\n");
agg_norm := agg_norm + combo_norm;
agg_trad_enum := agg_trad_enum + combo_trad_e;
agg_trad_norms := agg_trad_norms + combo_trad_n;
agg_trad_orbits := agg_trad_orbits + combo_trad_o;
agg_new_enum := agg_new_enum + combo_new_e;
agg_new_norms := agg_new_norms + combo_new_n;
agg_new_orbits := agg_new_orbits + combo_new_o;

Print("\n=== [5,4,3]/[3,2]_[4,4]_[5,2] (M=12, 2 H) ===\n");
S_M := SymmetricGroup(12);
combo_norm := 0; combo_trad_e := 0; combo_trad_n := 0; combo_trad_o := 0;
combo_new_e := 0; combo_new_n := 0; combo_new_o := 0;
H := Group([(1,2,3,4,5),(1,4)(2,3),(6,7,8),(7,8,9),(10,11,12),(10,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3,4,5),(1,4)(2,3)(10,11),(6,7,8),(7,8,9),(10,12,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
Print("  norm=", combo_norm, "ms  trad_enum=", combo_trad_e,"ms (",combo_trad_n," normals, ", combo_trad_o, " orbits)  new_enum=", combo_new_e, "ms (", combo_new_n, " normals, ",combo_new_o, " orbits)\n");
agg_norm := agg_norm + combo_norm;
agg_trad_enum := agg_trad_enum + combo_trad_e;
agg_trad_norms := agg_trad_norms + combo_trad_n;
agg_trad_orbits := agg_trad_orbits + combo_trad_o;
agg_new_enum := agg_new_enum + combo_new_e;
agg_new_norms := agg_new_norms + combo_new_n;
agg_new_orbits := agg_new_orbits + combo_new_o;

Print("\n=== [6,2,2,2]/[2,1]_[2,1]_[2,1]_[6,11] (M=12, 45 H) ===\n");
S_M := SymmetricGroup(12);
combo_norm := 0; combo_trad_e := 0; combo_trad_n := 0; combo_trad_o := 0;
combo_new_e := 0; combo_new_n := 0; combo_new_o := 0;
H := Group([(1,2)(3,4)(5,6),(9,12),(7,9,11)(8,10,12),(7,11)(8,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(3,4)(5,6)(7,11)(8,10),(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(3,4)(5,6)(9,12),(7,11,9)(8,12,10),(7,11)(8,10),(7,8,9)(10,11,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(3,4)(5,6)(7,11)(8,10),(7,11)(8,10)(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6),(3,4),(9,12),(7,9,11)(8,10,12),(7,11)(8,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6),(3,4)(7,11)(8,10),(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6),(3,4)(9,12),(7,11,9)(8,12,10),(7,11)(8,10),(7,11,12)(8,9,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6),(3,4)(7,11)(8,10),(7,11)(8,10)(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6)(7,11)(8,10),(3,4)(9,12),(7,11,9)(8,12,10),(7,11,12)(8,9,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6)(7,11)(8,10)(9,12),(3,4)(7,11)(8,10),(7,11,9)(8,12,10),(7,8,9)(10,11,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6)(9,12),(3,4)(7,11)(8,10)(9,12),(7,11,9)(8,12,10),(7,12,11)(8,10,9)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6)(7,11)(8,10),(3,4)(7,11)(8,10)(9,12),(7,11,9)(8,12,10),(7,12,8)(9,11,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6)(9,12),(3,4)(7,11)(8,10),(7,11,9)(8,12,10),(7,12,11)(8,10,9)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6)(7,11)(8,10)(9,12),(3,4)(9,12),(7,11,9)(8,12,10),(7,8,9)(10,11,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6)(7,11)(8,10),(3,4),(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6)(9,12),(3,4),(7,11,9)(8,12,10),(7,11)(8,10),(7,8,9)(10,11,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6)(7,11)(8,10),(3,4),(7,11)(8,10)(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6)(7,11)(8,10),(3,4)(7,11)(8,10),(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6)(9,12),(3,4)(9,12),(7,11,9)(8,12,10),(7,11)(8,10),(8,9)(11,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6)(7,11)(8,10),(3,4)(7,11)(8,10),(7,11)(8,10)(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6),(3,4)(5,6),(9,12),(7,9,11)(8,10,12),(7,11)(8,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6),(3,4)(5,6)(7,11)(8,10),(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6),(3,4)(5,6)(9,12),(7,11,9)(8,12,10),(7,11)(8,10),(7,12)(9,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6),(3,4)(5,6)(7,11)(8,10),(7,11)(8,10)(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,6)(7,11)(8,10),(3,4)(5,6)(9,12),(7,11,9)(8,12,10),(7,8,9)(10,11,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2),(3,4),(5,6),(9,12),(7,9,11)(8,10,12),(7,11)(8,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2),(3,4)(7,11)(8,10),(5,6),(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2),(3,4)(9,12),(5,6),(7,11,9)(8,12,10),(7,11)(8,10),(7,8)(10,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2),(3,4)(7,11)(8,10),(5,6),(7,11)(8,10)(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(9,12),(3,4)(7,11)(8,10),(5,6),(7,11,9)(8,12,10),(7,12,11)(8,10,9)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(7,11)(8,10),(3,4)(7,11)(8,10)(9,12),(5,6),(7,11,9)(8,12,10),(7,12,8)(9,11,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(7,11)(8,10)(9,12),(3,4)(9,12),(5,6),(7,11,9)(8,12,10),(7,12,11)(8,10,9)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(7,11)(8,10),(3,4)(7,11)(8,10),(5,6),(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(9,12),(3,4)(9,12),(5,6),(7,11,9)(8,12,10),(7,11)(8,10),(7,12,11)(8,10,9)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(7,11)(8,10),(3,4)(7,11)(8,10),(5,6),(7,11)(8,10)(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(9,12),(3,4)(7,11)(8,10),(5,6)(7,11)(8,10),(7,11,9)(8,12,10),(7,11,12)(8,9,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(7,11)(8,10),(3,4)(7,11)(8,10)(9,12),(5,6)(7,11)(8,10)(9,12),(7,11,9)(8,12,10),(7,12,11)(8,10,9)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(7,11)(8,10)(9,12),(3,4)(9,12),(5,6)(9,12),(7,11,9)(8,12,10),(7,12,8)(9,11,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(7,11)(8,10)(9,12),(3,4)(7,11)(8,10),(5,6)(7,11)(8,10),(7,11,9)(8,12,10),(7,12,8)(9,11,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(7,11)(8,10),(3,4)(9,12),(5,6)(9,12),(7,11,9)(8,12,10),(7,12,8)(9,11,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(9,12),(3,4)(7,11)(8,10)(9,12),(5,6)(7,11)(8,10)(9,12),(7,11,9)(8,12,10),(7,12,8)(9,11,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(7,11)(8,10),(3,4)(7,11)(8,10),(5,6)(7,11)(8,10),(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(9,12),(3,4)(9,12),(5,6)(9,12),(7,11,9)(8,12,10),(7,11)(8,10),(7,11,12)(8,9,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(7,11)(8,10),(3,4)(7,11)(8,10),(5,6)(7,11)(8,10),(7,11)(8,10)(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(9,12),(3,4)(7,11)(8,10)(9,12),(5,6)(7,11)(8,10),(7,11,9)(8,12,10),(7,12,8)(9,11,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
Print("  norm=", combo_norm, "ms  trad_enum=", combo_trad_e,"ms (",combo_trad_n," normals, ", combo_trad_o, " orbits)  new_enum=", combo_new_e, "ms (", combo_new_n, " normals, ",combo_new_o, " orbits)\n");
agg_norm := agg_norm + combo_norm;
agg_trad_enum := agg_trad_enum + combo_trad_e;
agg_trad_norms := agg_trad_norms + combo_trad_n;
agg_trad_orbits := agg_trad_orbits + combo_trad_o;
agg_new_enum := agg_new_enum + combo_new_e;
agg_new_norms := agg_new_norms + combo_new_n;
agg_new_orbits := agg_new_orbits + combo_new_o;

Print("\n=== [6,3,3]/[3,2]_[3,2]_[6,9] (M=12, 20 H) ===\n");
S_M := SymmetricGroup(12);
combo_norm := 0; combo_trad_e := 0; combo_trad_n := 0; combo_trad_o := 0;
combo_new_e := 0; combo_new_n := 0; combo_new_o := 0;
H := Group([(1,2,3),(1,2),(4,5,6),(4,5),(8,10,12),(7,11)(8,10),(7,10)(8,11)(9,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3),(1,2),(4,5,6),(4,5)(7,10)(8,11)(9,12),(8,12,10),(7,11)(8,10),(7,11,9)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3),(1,2),(4,5,6),(4,5)(7,11)(8,10),(8,12,10),(7,10)(8,11)(9,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3)(7,11,9)(8,10,12),(1,2)(7,12)(8,9)(10,11),(4,5,6)(7,11,9)(8,12,10),(4,5)(7,10)(8,9)(11,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3)(8,10,12),(1,2)(7,11)(8,12),(4,5,6),(4,5),(7,10)(8,11)(9,12),(7,8)(9,10)(11,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3)(8,12,10),(1,2)(7,8,11,12,9,10),(4,5,6),(4,5)(7,8)(9,12)(10,11),(7,9,11)(8,10,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3)(8,12,10),(1,2)(7,11)(10,12),(4,5,6),(4,5)(7,8)(9,12)(10,11),(7,9,11)(8,10,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3),(1,2)(7,10)(8,11)(9,12),(4,5,6),(4,5)(7,10)(8,11)(9,12),(8,12,10),(7,11)(8,10),(7,9,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3),(1,2)(7,11)(8,10),(4,5,6),(4,5)(7,11)(8,10),(8,12,10),(7,10)(8,11)(9,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3),(1,2)(7,11)(8,10),(4,5,6),(4,5)(7,10)(8,11)(9,12),(8,12,10),(7,9,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3),(1,2)(7,10)(8,11)(9,12),(4,5,6),(4,5)(7,8)(9,12)(10,11),(8,12,10),(7,9,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3),(1,2)(4,5),(4,6,5),(8,10,12),(7,11)(8,10),(7,10)(8,11)(9,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3),(1,2)(4,5)(7,10)(8,11)(9,12),(4,6,5),(8,12,10),(7,11)(8,10),(7,9,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3),(1,2)(4,5)(7,11)(8,10),(4,6,5),(8,12,10),(7,10)(8,11)(9,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3)(8,10,12),(1,2)(4,5)(7,11)(8,12),(4,6,5),(7,10)(8,11)(9,12),(7,12)(8,9)(10,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3)(8,10,12),(1,2)(4,5)(7,11)(8,10),(4,6,5)(8,10,12),(7,10)(8,11)(9,12),(7,12)(8,9)(10,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3)(4,5,6),(1,2)(4,5),(8,10,12),(7,11)(8,10),(7,10)(8,11)(9,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3)(4,5,6),(1,2)(4,5)(7,10)(8,11)(9,12),(8,12,10),(7,11)(8,10),(7,9,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3)(4,5,6),(1,2)(4,5)(7,11)(8,10),(8,12,10),(7,10)(8,11)(9,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2,3)(4,5,6)(8,10,12),(1,2)(4,5)(7,11)(8,12),(7,10)(8,11)(9,12),(7,12)(8,9)(10,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
Print("  norm=", combo_norm, "ms  trad_enum=", combo_trad_e,"ms (",combo_trad_n," normals, ", combo_trad_o, " orbits)  new_enum=", combo_new_e, "ms (", combo_new_n, " normals, ",combo_new_o, " orbits)\n");
agg_norm := agg_norm + combo_norm;
agg_trad_enum := agg_trad_enum + combo_trad_e;
agg_trad_norms := agg_trad_norms + combo_trad_n;
agg_trad_orbits := agg_trad_orbits + combo_trad_o;
agg_new_enum := agg_new_enum + combo_new_e;
agg_new_norms := agg_new_norms + combo_new_n;
agg_new_orbits := agg_new_orbits + combo_new_o;

Print("\n=== [8,2,2]/[2,1]_[2,1]_[8,38] (M=12, 5 H) ===\n");
S_M := SymmetricGroup(12);
combo_norm := 0; combo_trad_e := 0; combo_trad_n := 0; combo_trad_o := 0;
combo_new_e := 0; combo_new_n := 0; combo_new_o := 0;
H := Group([(1,2)(3,4),(8,12),(5,12)(6,7)(8,9)(10,11),(5,6,7)(9,10,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(3,4)(8,12),(5,12)(6,7)(8,9)(10,11),(5,7,6)(9,11,10),(6,11,8)(7,12,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2),(3,4),(8,12),(5,12)(6,7)(8,9)(10,11),(5,6,7)(9,10,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2),(3,4)(8,12),(5,12)(6,7)(8,9)(10,11),(5,7,6)(9,11,10),(5,8)(6,7)(9,12)(10,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(8,12),(3,4)(8,12),(5,12)(6,7)(8,9)(10,11),(5,7,6)(9,11,10),(5,6,8)(9,10,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
Print("  norm=", combo_norm, "ms  trad_enum=", combo_trad_e,"ms (",combo_trad_n," normals, ", combo_trad_o, " orbits)  new_enum=", combo_new_e, "ms (", combo_new_n, " normals, ",combo_new_o, " orbits)\n");
agg_norm := agg_norm + combo_norm;
agg_trad_enum := agg_trad_enum + combo_trad_e;
agg_trad_norms := agg_trad_norms + combo_trad_n;
agg_trad_orbits := agg_trad_orbits + combo_trad_o;
agg_new_enum := agg_new_enum + combo_new_e;
agg_new_norms := agg_new_norms + combo_new_n;
agg_new_orbits := agg_new_orbits + combo_new_o;

Print("\n=== [8,2,2]/[2,1]_[2,1]_[8,42] (M=12, 5 H) ===\n");
S_M := SymmetricGroup(12);
combo_norm := 0; combo_trad_e := 0; combo_trad_n := 0; combo_trad_o := 0;
combo_new_e := 0; combo_new_n := 0; combo_new_o := 0;
H := Group([(1,2)(3,4),(5,7)(6,12),(5,6,7),(5,9)(6,10)(7,11)(8,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(3,4)(5,9)(6,10)(7,11)(8,12),(5,7)(6,12),(5,7,6),(8,11,9),(5,12,7)(8,9,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2),(3,4),(5,7)(6,12),(5,6,7),(5,9)(6,10)(7,11)(8,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2),(3,4)(5,9)(6,10)(7,11)(8,12),(5,7)(6,12),(5,7,6),(8,11,9),(8,9,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(1,2)(5,9)(6,10)(7,11)(8,12),(3,4)(5,9)(6,10)(7,11)(8,12),(5,7)(6,12),(5,7,6),(8,9,10),(8,11)(9,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
Print("  norm=", combo_norm, "ms  trad_enum=", combo_trad_e,"ms (",combo_trad_n," normals, ", combo_trad_o, " orbits)  new_enum=", combo_new_e, "ms (", combo_new_n, " normals, ",combo_new_o, " orbits)\n");
agg_norm := agg_norm + combo_norm;
agg_trad_enum := agg_trad_enum + combo_trad_e;
agg_trad_norms := agg_trad_norms + combo_trad_n;
agg_trad_orbits := agg_trad_orbits + combo_trad_o;
agg_new_enum := agg_new_enum + combo_new_e;
agg_new_norms := agg_new_norms + combo_new_n;
agg_new_orbits := agg_new_orbits + combo_new_o;

Print("\n=== [8,4]/[4,4]_[8,15] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
combo_norm := 0; combo_trad_e := 0; combo_trad_n := 0; combo_trad_o := 0;
combo_new_e := 0; combo_new_n := 0; combo_new_o := 0;
H := Group([(1,2,3,4,5,6,7,8),(1,5)(3,7),(1,6)(2,5)(3,4)(7,8),(9,10,11),(10,11,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
Print("  norm=", combo_norm, "ms  trad_enum=", combo_trad_e,"ms (",combo_trad_n," normals, ", combo_trad_o, " orbits)  new_enum=", combo_new_e, "ms (", combo_new_n, " normals, ",combo_new_o, " orbits)\n");
agg_norm := agg_norm + combo_norm;
agg_trad_enum := agg_trad_enum + combo_trad_e;
agg_trad_norms := agg_trad_norms + combo_trad_n;
agg_trad_orbits := agg_trad_orbits + combo_trad_o;
agg_new_enum := agg_new_enum + combo_new_e;
agg_new_norms := agg_new_norms + combo_new_n;
agg_new_orbits := agg_new_orbits + combo_new_o;

Print("\n=== [8,4]/[4,5]_[8,44] (M=12, 6 H) ===\n");
S_M := SymmetricGroup(12);
combo_norm := 0; combo_trad_e := 0; combo_trad_n := 0; combo_trad_o := 0;
combo_new_e := 0; combo_new_n := 0; combo_new_o := 0;
H := Group([(4,8),(1,8)(4,5),(1,2,3,8)(4,5,6,7),(9,10,11,12),(9,10)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(4,8),(1,8)(4,5)(9,10),(1,2,3,8)(4,5,6,7)(9,10),(10,12,11),(9,12,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(4,8),(1,8)(4,5)(9,11,12,10),(1,2,3,8)(4,5,6,7)(9,12,11,10),(9,11)(10,12),(9,12)(10,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(4,8),(1,8)(4,5)(10,12),(1,2,3,8)(4,5,6,7)(9,11,10,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(4,8)(9,10),(1,8)(4,5),(1,2,3,8)(4,5,6,7),(10,12,11),(9,12,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
H := Group([(4,8)(9,10),(1,8)(4,5)(9,10),(1,2,3,8)(4,5,6,7)(9,10),(10,12,11),(9,12,11)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
Print("  norm=", combo_norm, "ms  trad_enum=", combo_trad_e,"ms (",combo_trad_n," normals, ", combo_trad_o, " orbits)  new_enum=", combo_new_e, "ms (", combo_new_n, " normals, ",combo_new_o, " orbits)\n");
agg_norm := agg_norm + combo_norm;
agg_trad_enum := agg_trad_enum + combo_trad_e;
agg_trad_norms := agg_trad_norms + combo_trad_n;
agg_trad_orbits := agg_trad_orbits + combo_trad_o;
agg_new_enum := agg_new_enum + combo_new_e;
agg_new_norms := agg_new_norms + combo_new_n;
agg_new_orbits := agg_new_orbits + combo_new_o;

Print("\n=== [9,3]/[3,1]_[9,29] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
combo_norm := 0; combo_trad_e := 0; combo_trad_n := 0; combo_trad_o := 0;
combo_new_e := 0; combo_new_n := 0; combo_new_o := 0;
H := Group([(1,2,9),(4,5)(7,8),(1,4,7)(2,5,8)(3,6,9),(3,6)(4,7)(5,8),(10,11,12)]);
res := TimeOneH(H, S_M);
combo_norm := combo_norm + res.norm_ms;
combo_trad_e := combo_trad_e + res.trad_enum_ms;
combo_trad_n := combo_trad_n + res.trad_normals;
combo_trad_o := combo_trad_o + res.trad_orbits;
combo_new_e := combo_new_e + res.new_enum_ms;
combo_new_n := combo_new_n + res.new_normals;
combo_new_o := combo_new_o + res.new_orbits;
agg_h := agg_h + 1;
Print("  norm=", combo_norm, "ms  trad_enum=", combo_trad_e,"ms (",combo_trad_n," normals, ", combo_trad_o, " orbits)  new_enum=", combo_new_e, "ms (", combo_new_n, " normals, ",combo_new_o, " orbits)\n");
agg_norm := agg_norm + combo_norm;
agg_trad_enum := agg_trad_enum + combo_trad_e;
agg_trad_norms := agg_trad_norms + combo_trad_n;
agg_trad_orbits := agg_trad_orbits + combo_trad_o;
agg_new_enum := agg_new_enum + combo_new_e;
agg_new_norms := agg_new_norms + combo_new_n;
agg_new_orbits := agg_new_orbits + combo_new_o;

Print("\n=== AGGREGATE ===\n");
Print("Total H:               ", agg_h, "\n");
Print("Total Normalizer time: ", agg_norm, "ms\n");
Print("Traditional (NS+all):  enum=", agg_trad_enum, "ms  ", agg_trad_norms, " normals  ", agg_trad_orbits, " orbits\n");
Print("S3-only (tiered):      enum=", agg_new_enum, "ms  ", agg_new_norms, " normals  ", agg_new_orbits, " orbits\n");
if agg_new_enum > 0 then
    Print("Speedup ratio (enum):  ", Float(agg_trad_enum * 1.0 / agg_new_enum), "x\n");
fi;
LogTo();
QUIT;
