LogTo("C:/Users/jeffr/Downloads/Lifting/compare_unified_vs_tiered_s12.log");
Print("=== TRAD-S vs TRAD-W vs TIERED-W on 20 S12 combos ===\n");

Q_C2 := CyclicGroup(IsPermGroup, 2);
Q_C3 := CyclicGroup(IsPermGroup, 3);
Q_S3 := SymmetricGroup(3);
Q_GROUPS := [Q_C2, Q_C3, Q_S3];
Q_SIZE_FILTER := [1, 2, 3, 6];

ConjAction := function(K, g) return K^g; end;
SafeId := function(G)
    local n;
    n := Size(G);
    if IdGroupsAvailable(n) then return [n, 0, IdGroup(G)]; fi;
    return [n, 1, AbelianInvariants(G), List(DerivedSeries(G), Size)];
end;

BlockWreathFromPartition := function(partition)
    local factors, i, j, m, mult;
    factors := [];
    i := 1;
    while i <= Length(partition) do
        m := partition[i];
        mult := 0; j := i;
        while j <= Length(partition) and partition[j] = m do
            mult := mult + 1; j := j + 1;
        od;
        if mult = 1 then Add(factors, SymmetricGroup(m));
        else Add(factors, WreathProduct(SymmetricGroup(m), SymmetricGroup(mult)));
        fi;
        i := j;
    od;
    if Length(factors) = 1 then return factors[1]; fi;
    return DirectProduct(factors);
end;

_IndexPNormals := function(H, p)
    local DH, hom, A, max_subs;
    DH := DerivedSubgroup(H);
    if Index(H, DH) mod p <> 0 then return []; fi;
    hom := NaturalHomomorphismByNormalSubgroup(H, DH);
    A := Range(hom);
    max_subs := Filtered(MaximalSubgroupClassReps(A), K -> Index(A, K) = p);
    return List(max_subs, K -> PreImage(hom, K));
end;

_TieredEnumerate := function(H)
    local result, Q, sz;
    result := [];
    for Q in Q_GROUPS do
        sz := Size(Q);
        if IsPrimeInt(sz) then
            Append(result, _IndexPNormals(H, sz));
        else
            Append(result, Set(List(GQuotients(H, Q), Kernel)));
        fi;
    od;
    return Set(result);
end;

_OrbitRecs := function(H, N, normals)
    local K_orbit, K_H, hom_H, Q_H, Stab, orbits;
    orbits := [];
    for K_orbit in Orbits(N, normals, ConjAction) do
        K_H := K_orbit[1];
        hom_H := NaturalHomomorphismByNormalSubgroup(H, K_H);
        Q_H := Range(hom_H);
        Stab := Stabilizer(N, K_H, ConjAction);
        Add(orbits, rec(qsize := Size(Q_H), qid := SafeId(Q_H)));
    od;
    return orbits;
end;

TimeOneH := function(H, S_M, W_ML)
    local norm_S_t, N_S, norm_W_t, N_W,
          ns_t, ns, filt_t, ns_filt,
          trad_S_orb_t, trad_S_orbs,
          trad_W_orb_t, trad_W_orbs,
          tier_t, tier_kers, tier_W_orb_t, tier_W_orbs;
    norm_S_t := Runtime();
    N_S := Normalizer(S_M, H);
    norm_S_t := Runtime() - norm_S_t;
    norm_W_t := Runtime();
    N_W := Normalizer(W_ML, H);
    norm_W_t := Runtime() - norm_W_t;
    ns_t := Runtime();
    ns := NormalSubgroups(H);
    ns_t := Runtime() - ns_t;
    filt_t := Runtime();
    ns_filt := Filtered(ns, K -> K <> H and Size(H)/Size(K) in Q_SIZE_FILTER);
    filt_t := Runtime() - filt_t;
    trad_S_orb_t := Runtime();
    trad_S_orbs := _OrbitRecs(H, N_S, ns_filt);
    trad_S_orb_t := Runtime() - trad_S_orb_t;
    trad_W_orb_t := Runtime();
    trad_W_orbs := _OrbitRecs(H, N_W, ns_filt);
    trad_W_orb_t := Runtime() - trad_W_orb_t;
    tier_t := Runtime();
    tier_kers := _TieredEnumerate(H);
    tier_t := Runtime() - tier_t;
    tier_W_orb_t := Runtime();
    tier_W_orbs := _OrbitRecs(H, N_W, tier_kers);
    tier_W_orb_t := Runtime() - tier_W_orb_t;
    return rec(
        norm_S := norm_S_t, norm_W := norm_W_t,
        ns := ns_t, filt := filt_t,
        ns_count := Length(ns), ns_filt_count := Length(ns_filt),
        tier_count := Length(tier_kers),
        trad_S_orb := trad_S_orb_t, trad_S_n := Length(trad_S_orbs),
        trad_W_orb := trad_W_orb_t, trad_W_n := Length(trad_W_orbs),
        tier := tier_t, tier_W_orb := tier_W_orb_t, tier_W_n := Length(tier_W_orbs)
    );
end;

agg := rec(
    norm_S := 0, norm_W := 0,
    ns := 0, filt := 0,
    trad_S_orb := 0, trad_W_orb := 0,
    tier := 0, tier_W_orb := 0, h := 0
);

Print("\n=== [12]/[12,106] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
W_ML := BlockWreathFromPartition([12]);
cb := rec(norm_S := 0, norm_W := 0, ns := 0, filt := 0, trad_S_orb := 0, trad_W_orb := 0, tier := 0, tier_W_orb := 0);
H := Group([(1,12)(2,3),(1,12)(4,5),(1,12)(6,7),(1,5,9)(2,6,10)(3,7,11)(4,8,12),(1,11)(2,8)(3,9)(4,6)(5,7)(10,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
Print("  TRAD-S=", cb.norm_S + cb.ns + cb.filt + cb.trad_S_orb,"ms  TRAD-W=", cb.norm_W + cb.ns + cb.filt + cb.trad_W_orb,"ms  TIERED-W=", cb.norm_W + cb.tier + cb.tier_W_orb, "ms"); 
Print(" (norm_S=", cb.norm_S, " norm_W=", cb.norm_W, " ns=", cb.ns," filt=", cb.filt, " orb_S=", cb.trad_S_orb, " orb_W=", cb.trad_W_orb," tier_enum=", cb.tier, " tier_orb=", cb.tier_W_orb, ")\n");
agg.norm_S := agg.norm_S + cb.norm_S;
agg.norm_W := agg.norm_W + cb.norm_W;
agg.ns := agg.ns + cb.ns;
agg.filt := agg.filt + cb.filt;
agg.trad_S_orb := agg.trad_S_orb + cb.trad_S_orb;
agg.trad_W_orb := agg.trad_W_orb + cb.trad_W_orb;
agg.tier := agg.tier + cb.tier;
agg.tier_W_orb := agg.tier_W_orb + cb.tier_W_orb;

Print("\n=== [12]/[12,109] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
W_ML := BlockWreathFromPartition([12]);
cb := rec(norm_S := 0, norm_W := 0, ns := 0, filt := 0, trad_S_orb := 0, trad_W_orb := 0, tier := 0, tier_W_orb := 0);
H := Group([(1,12)(4,5),(1,12)(8,9),(1,3,5,7,9,11)(2,4,6,8,10,12),(1,11)(2,8)(3,9)(4,6)(5,7)(10,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
Print("  TRAD-S=", cb.norm_S + cb.ns + cb.filt + cb.trad_S_orb,"ms  TRAD-W=", cb.norm_W + cb.ns + cb.filt + cb.trad_W_orb,"ms  TIERED-W=", cb.norm_W + cb.tier + cb.tier_W_orb, "ms"); 
Print(" (norm_S=", cb.norm_S, " norm_W=", cb.norm_W, " ns=", cb.ns," filt=", cb.filt, " orb_S=", cb.trad_S_orb, " orb_W=", cb.trad_W_orb," tier_enum=", cb.tier, " tier_orb=", cb.tier_W_orb, ")\n");
agg.norm_S := agg.norm_S + cb.norm_S;
agg.norm_W := agg.norm_W + cb.norm_W;
agg.ns := agg.ns + cb.ns;
agg.filt := agg.filt + cb.filt;
agg.trad_S_orb := agg.trad_S_orb + cb.trad_S_orb;
agg.trad_W_orb := agg.trad_W_orb + cb.trad_W_orb;
agg.tier := agg.tier + cb.tier;
agg.tier_W_orb := agg.tier_W_orb + cb.tier_W_orb;

Print("\n=== [12]/[12,115] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
W_ML := BlockWreathFromPartition([12]);
cb := rec(norm_S := 0, norm_W := 0, ns := 0, filt := 0, trad_S_orb := 0, trad_W_orb := 0, tier := 0, tier_W_orb := 0);
H := Group([(1,12)(2,3)(6,7)(8,9),(1,12)(2,3)(4,5),(1,5,9)(2,6,10)(3,7,11)(4,8,12),(2,4)(3,5)(6,7)(8,10)(9,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
Print("  TRAD-S=", cb.norm_S + cb.ns + cb.filt + cb.trad_S_orb,"ms  TRAD-W=", cb.norm_W + cb.ns + cb.filt + cb.trad_W_orb,"ms  TIERED-W=", cb.norm_W + cb.tier + cb.tier_W_orb, "ms"); 
Print(" (norm_S=", cb.norm_S, " norm_W=", cb.norm_W, " ns=", cb.ns," filt=", cb.filt, " orb_S=", cb.trad_S_orb, " orb_W=", cb.trad_W_orb," tier_enum=", cb.tier, " tier_orb=", cb.tier_W_orb, ")\n");
agg.norm_S := agg.norm_S + cb.norm_S;
agg.norm_W := agg.norm_W + cb.norm_W;
agg.ns := agg.ns + cb.ns;
agg.filt := agg.filt + cb.filt;
agg.trad_S_orb := agg.trad_S_orb + cb.trad_S_orb;
agg.trad_W_orb := agg.trad_W_orb + cb.trad_W_orb;
agg.tier := agg.tier + cb.tier;
agg.tier_W_orb := agg.tier_W_orb + cb.tier_W_orb;

Print("\n=== [12]/[12,119] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
W_ML := BlockWreathFromPartition([12]);
cb := rec(norm_S := 0, norm_W := 0, ns := 0, filt := 0, trad_S_orb := 0, trad_W_orb := 0, tier := 0, tier_W_orb := 0);
H := Group([(2,6,10)(3,7,11)(4,8,12),(1,5)(2,10)(4,8)(7,11),(1,4,7,10)(2,5,8,11)(3,6,9,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
Print("  TRAD-S=", cb.norm_S + cb.ns + cb.filt + cb.trad_S_orb,"ms  TRAD-W=", cb.norm_W + cb.ns + cb.filt + cb.trad_W_orb,"ms  TIERED-W=", cb.norm_W + cb.tier + cb.tier_W_orb, "ms"); 
Print(" (norm_S=", cb.norm_S, " norm_W=", cb.norm_W, " ns=", cb.ns," filt=", cb.filt, " orb_S=", cb.trad_S_orb, " orb_W=", cb.trad_W_orb," tier_enum=", cb.tier, " tier_orb=", cb.tier_W_orb, ")\n");
agg.norm_S := agg.norm_S + cb.norm_S;
agg.norm_W := agg.norm_W + cb.norm_W;
agg.ns := agg.ns + cb.ns;
agg.filt := agg.filt + cb.filt;
agg.trad_S_orb := agg.trad_S_orb + cb.trad_S_orb;
agg.trad_W_orb := agg.trad_W_orb + cb.trad_W_orb;
agg.tier := agg.tier + cb.tier;
agg.tier_W_orb := agg.tier_W_orb + cb.tier_W_orb;

Print("\n=== [12]/[12,220] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
W_ML := BlockWreathFromPartition([12]);
cb := rec(norm_S := 0, norm_W := 0, ns := 0, filt := 0, trad_S_orb := 0, trad_W_orb := 0, tier := 0, tier_W_orb := 0);
H := Group([(1,3,5)(2,4,12)(7,9,11),(1,7,3,9,5)(2,4,6,8,10),(1,9)(2,12)(3,7)(5,11),(1,12)(2,3)(4,11)(5,10)(6,9)(7,8)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
Print("  TRAD-S=", cb.norm_S + cb.ns + cb.filt + cb.trad_S_orb,"ms  TRAD-W=", cb.norm_W + cb.ns + cb.filt + cb.trad_W_orb,"ms  TIERED-W=", cb.norm_W + cb.tier + cb.tier_W_orb, "ms"); 
Print(" (norm_S=", cb.norm_S, " norm_W=", cb.norm_W, " ns=", cb.ns," filt=", cb.filt, " orb_S=", cb.trad_S_orb, " orb_W=", cb.trad_W_orb," tier_enum=", cb.tier, " tier_orb=", cb.tier_W_orb, ")\n");
agg.norm_S := agg.norm_S + cb.norm_S;
agg.norm_W := agg.norm_W + cb.norm_W;
agg.ns := agg.ns + cb.ns;
agg.filt := agg.filt + cb.filt;
agg.trad_S_orb := agg.trad_S_orb + cb.trad_S_orb;
agg.trad_W_orb := agg.trad_W_orb + cb.trad_W_orb;
agg.tier := agg.tier + cb.tier;
agg.tier_W_orb := agg.tier_W_orb + cb.tier_W_orb;

Print("\n=== [12]/[12,232] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
W_ML := BlockWreathFromPartition([12]);
cb := rec(norm_S := 0, norm_W := 0, ns := 0, filt := 0, trad_S_orb := 0, trad_W_orb := 0, tier := 0, tier_W_orb := 0);
H := Group([(4,8,12),(1,5)(2,10)(4,8)(7,11),(1,7,10)(2,5,11)(3,6,9),(2,8,7)(3,6,12)(4,11,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
Print("  TRAD-S=", cb.norm_S + cb.ns + cb.filt + cb.trad_S_orb,"ms  TRAD-W=", cb.norm_W + cb.ns + cb.filt + cb.trad_W_orb,"ms  TIERED-W=", cb.norm_W + cb.tier + cb.tier_W_orb, "ms"); 
Print(" (norm_S=", cb.norm_S, " norm_W=", cb.norm_W, " ns=", cb.ns," filt=", cb.filt, " orb_S=", cb.trad_S_orb, " orb_W=", cb.trad_W_orb," tier_enum=", cb.tier, " tier_orb=", cb.tier_W_orb, ")\n");
agg.norm_S := agg.norm_S + cb.norm_S;
agg.norm_W := agg.norm_W + cb.norm_W;
agg.ns := agg.ns + cb.ns;
agg.filt := agg.filt + cb.filt;
agg.trad_S_orb := agg.trad_S_orb + cb.trad_S_orb;
agg.trad_W_orb := agg.trad_W_orb + cb.trad_W_orb;
agg.tier := agg.tier + cb.tier;
agg.tier_W_orb := agg.tier_W_orb + cb.tier_W_orb;

Print("\n=== [12]/[12,249] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
W_ML := BlockWreathFromPartition([12]);
cb := rec(norm_S := 0, norm_W := 0, ns := 0, filt := 0, trad_S_orb := 0, trad_W_orb := 0, tier := 0, tier_W_orb := 0);
H := Group([(4,8,12),(2,10)(4,8),(2,8,10,4)(6,12),(1,12)(2,3)(4,5)(6,7)(8,9)(10,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
Print("  TRAD-S=", cb.norm_S + cb.ns + cb.filt + cb.trad_S_orb,"ms  TRAD-W=", cb.norm_W + cb.ns + cb.filt + cb.trad_W_orb,"ms  TIERED-W=", cb.norm_W + cb.tier + cb.tier_W_orb, "ms"); 
Print(" (norm_S=", cb.norm_S, " norm_W=", cb.norm_W, " ns=", cb.ns," filt=", cb.filt, " orb_S=", cb.trad_S_orb, " orb_W=", cb.trad_W_orb," tier_enum=", cb.tier, " tier_orb=", cb.tier_W_orb, ")\n");
agg.norm_S := agg.norm_S + cb.norm_S;
agg.norm_W := agg.norm_W + cb.norm_W;
agg.ns := agg.ns + cb.ns;
agg.filt := agg.filt + cb.filt;
agg.trad_S_orb := agg.trad_S_orb + cb.trad_S_orb;
agg.trad_W_orb := agg.trad_W_orb + cb.trad_W_orb;
agg.tier := agg.tier + cb.tier;
agg.tier_W_orb := agg.tier_W_orb + cb.tier_W_orb;

Print("\n=== [12]/[12,266] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
W_ML := BlockWreathFromPartition([12]);
cb := rec(norm_S := 0, norm_W := 0, ns := 0, filt := 0, trad_S_orb := 0, trad_W_orb := 0, tier := 0, tier_W_orb := 0);
H := Group([(4,8,12),(2,10)(4,8),(1,10)(2,5)(3,12)(4,7)(6,9)(8,11),(1,7)(2,8)(3,9)(4,10)(5,11)(6,12),(1,7,5,11)(2,10)(3,9)(4,8)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
Print("  TRAD-S=", cb.norm_S + cb.ns + cb.filt + cb.trad_S_orb,"ms  TRAD-W=", cb.norm_W + cb.ns + cb.filt + cb.trad_W_orb,"ms  TIERED-W=", cb.norm_W + cb.tier + cb.tier_W_orb, "ms"); 
Print(" (norm_S=", cb.norm_S, " norm_W=", cb.norm_W, " ns=", cb.ns," filt=", cb.filt, " orb_S=", cb.trad_S_orb, " orb_W=", cb.trad_W_orb," tier_enum=", cb.tier, " tier_orb=", cb.tier_W_orb, ")\n");
agg.norm_S := agg.norm_S + cb.norm_S;
agg.norm_W := agg.norm_W + cb.norm_W;
agg.ns := agg.ns + cb.ns;
agg.filt := agg.filt + cb.filt;
agg.trad_S_orb := agg.trad_S_orb + cb.trad_S_orb;
agg.trad_W_orb := agg.trad_W_orb + cb.trad_W_orb;
agg.tier := agg.tier + cb.tier;
agg.tier_W_orb := agg.tier_W_orb + cb.tier_W_orb;

Print("\n=== [12]/[12,45] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
W_ML := BlockWreathFromPartition([12]);
cb := rec(norm_S := 0, norm_W := 0, ns := 0, filt := 0, trad_S_orb := 0, trad_W_orb := 0, tier := 0, tier_W_orb := 0);
H := Group([(1,4,7,10)(2,5,8,11)(3,6,9,12),(1,10)(2,5)(6,9),(1,5,9)(2,6,10)(3,7,11)(4,8,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
Print("  TRAD-S=", cb.norm_S + cb.ns + cb.filt + cb.trad_S_orb,"ms  TRAD-W=", cb.norm_W + cb.ns + cb.filt + cb.trad_W_orb,"ms  TIERED-W=", cb.norm_W + cb.tier + cb.tier_W_orb, "ms"); 
Print(" (norm_S=", cb.norm_S, " norm_W=", cb.norm_W, " ns=", cb.ns," filt=", cb.filt, " orb_S=", cb.trad_S_orb, " orb_W=", cb.trad_W_orb," tier_enum=", cb.tier, " tier_orb=", cb.tier_W_orb, ")\n");
agg.norm_S := agg.norm_S + cb.norm_S;
agg.norm_W := agg.norm_W + cb.norm_W;
agg.ns := agg.ns + cb.ns;
agg.filt := agg.filt + cb.filt;
agg.trad_S_orb := agg.trad_S_orb + cb.trad_S_orb;
agg.trad_W_orb := agg.trad_W_orb + cb.trad_W_orb;
agg.tier := agg.tier + cb.tier;
agg.tier_W_orb := agg.tier_W_orb + cb.tier_W_orb;

Print("\n=== [4,4,4]/[4,2]_[4,2]_[4,4] (M=12, 3 H) ===\n");
S_M := SymmetricGroup(12);
W_ML := BlockWreathFromPartition([4,4,4]);
cb := rec(norm_S := 0, norm_W := 0, ns := 0, filt := 0, trad_S_orb := 0, trad_W_orb := 0, tier := 0, tier_W_orb := 0);
H := Group([(1,4)(2,3),(1,2)(3,4),(5,8)(6,7),(5,6)(7,8),(9,10,11),(10,11,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,4)(2,3),(1,2)(3,4)(5,6)(7,8),(5,8)(6,7),(9,10,11),(10,11,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,4)(2,3)(5,8)(6,7),(1,2)(3,4)(5,6)(7,8),(9,10,11),(10,11,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
Print("  TRAD-S=", cb.norm_S + cb.ns + cb.filt + cb.trad_S_orb,"ms  TRAD-W=", cb.norm_W + cb.ns + cb.filt + cb.trad_W_orb,"ms  TIERED-W=", cb.norm_W + cb.tier + cb.tier_W_orb, "ms"); 
Print(" (norm_S=", cb.norm_S, " norm_W=", cb.norm_W, " ns=", cb.ns," filt=", cb.filt, " orb_S=", cb.trad_S_orb, " orb_W=", cb.trad_W_orb," tier_enum=", cb.tier, " tier_orb=", cb.tier_W_orb, ")\n");
agg.norm_S := agg.norm_S + cb.norm_S;
agg.norm_W := agg.norm_W + cb.norm_W;
agg.ns := agg.ns + cb.ns;
agg.filt := agg.filt + cb.filt;
agg.trad_S_orb := agg.trad_S_orb + cb.trad_S_orb;
agg.trad_W_orb := agg.trad_W_orb + cb.trad_W_orb;
agg.tier := agg.tier + cb.tier;
agg.tier_W_orb := agg.tier_W_orb + cb.tier_W_orb;

Print("\n=== [5,4,3]/[3,1]_[4,3]_[5,3] (M=12, 4 H) ===\n");
S_M := SymmetricGroup(12);
W_ML := BlockWreathFromPartition([5,4,3]);
cb := rec(norm_S := 0, norm_W := 0, ns := 0, filt := 0, trad_S_orb := 0, trad_W_orb := 0, tier := 0, tier_W_orb := 0);
H := Group([(1,2,3,4,5),(1,2,4,3),(6,7,8),(9,10,11,12),(9,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3,4,5),(1,2,4,3)(9,11),(6,7,8),(9,12,11,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3,4,5),(1,2,4,3)(9,10,11,12),(6,7,8),(9,11)(10,12),(9,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3,4,5),(1,2,4,3)(9,11),(6,7,8),(9,10)(11,12),(9,12)(10,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
Print("  TRAD-S=", cb.norm_S + cb.ns + cb.filt + cb.trad_S_orb,"ms  TRAD-W=", cb.norm_W + cb.ns + cb.filt + cb.trad_W_orb,"ms  TIERED-W=", cb.norm_W + cb.tier + cb.tier_W_orb, "ms"); 
Print(" (norm_S=", cb.norm_S, " norm_W=", cb.norm_W, " ns=", cb.ns," filt=", cb.filt, " orb_S=", cb.trad_S_orb, " orb_W=", cb.trad_W_orb," tier_enum=", cb.tier, " tier_orb=", cb.tier_W_orb, ")\n");
agg.norm_S := agg.norm_S + cb.norm_S;
agg.norm_W := agg.norm_W + cb.norm_W;
agg.ns := agg.ns + cb.ns;
agg.filt := agg.filt + cb.filt;
agg.trad_S_orb := agg.trad_S_orb + cb.trad_S_orb;
agg.trad_W_orb := agg.trad_W_orb + cb.trad_W_orb;
agg.tier := agg.tier + cb.tier;
agg.tier_W_orb := agg.tier_W_orb + cb.tier_W_orb;

Print("\n=== [5,4,3]/[3,1]_[4,5]_[5,3] (M=12, 2 H) ===\n");
S_M := SymmetricGroup(12);
W_ML := BlockWreathFromPartition([5,4,3]);
cb := rec(norm_S := 0, norm_W := 0, ns := 0, filt := 0, trad_S_orb := 0, trad_W_orb := 0, tier := 0, tier_W_orb := 0);
H := Group([(1,2,3,4,5),(1,2,4,3),(6,7,8),(9,10,11,12),(9,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3,4,5),(1,2,4,3)(9,10),(6,7,8),(10,12,11),(9,12,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
Print("  TRAD-S=", cb.norm_S + cb.ns + cb.filt + cb.trad_S_orb,"ms  TRAD-W=", cb.norm_W + cb.ns + cb.filt + cb.trad_W_orb,"ms  TIERED-W=", cb.norm_W + cb.tier + cb.tier_W_orb, "ms"); 
Print(" (norm_S=", cb.norm_S, " norm_W=", cb.norm_W, " ns=", cb.ns," filt=", cb.filt, " orb_S=", cb.trad_S_orb, " orb_W=", cb.trad_W_orb," tier_enum=", cb.tier, " tier_orb=", cb.tier_W_orb, ")\n");
agg.norm_S := agg.norm_S + cb.norm_S;
agg.norm_W := agg.norm_W + cb.norm_W;
agg.ns := agg.ns + cb.ns;
agg.filt := agg.filt + cb.filt;
agg.trad_S_orb := agg.trad_S_orb + cb.trad_S_orb;
agg.trad_W_orb := agg.trad_W_orb + cb.trad_W_orb;
agg.tier := agg.tier + cb.tier;
agg.tier_W_orb := agg.tier_W_orb + cb.tier_W_orb;

Print("\n=== [5,4,3]/[3,2]_[4,4]_[5,2] (M=12, 2 H) ===\n");
S_M := SymmetricGroup(12);
W_ML := BlockWreathFromPartition([5,4,3]);
cb := rec(norm_S := 0, norm_W := 0, ns := 0, filt := 0, trad_S_orb := 0, trad_W_orb := 0, tier := 0, tier_W_orb := 0);
H := Group([(1,2,3,4,5),(1,4)(2,3),(6,7,8),(7,8,9),(10,11,12),(10,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3,4,5),(1,4)(2,3)(10,11),(6,7,8),(7,8,9),(10,12,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
Print("  TRAD-S=", cb.norm_S + cb.ns + cb.filt + cb.trad_S_orb,"ms  TRAD-W=", cb.norm_W + cb.ns + cb.filt + cb.trad_W_orb,"ms  TIERED-W=", cb.norm_W + cb.tier + cb.tier_W_orb, "ms"); 
Print(" (norm_S=", cb.norm_S, " norm_W=", cb.norm_W, " ns=", cb.ns," filt=", cb.filt, " orb_S=", cb.trad_S_orb, " orb_W=", cb.trad_W_orb," tier_enum=", cb.tier, " tier_orb=", cb.tier_W_orb, ")\n");
agg.norm_S := agg.norm_S + cb.norm_S;
agg.norm_W := agg.norm_W + cb.norm_W;
agg.ns := agg.ns + cb.ns;
agg.filt := agg.filt + cb.filt;
agg.trad_S_orb := agg.trad_S_orb + cb.trad_S_orb;
agg.trad_W_orb := agg.trad_W_orb + cb.trad_W_orb;
agg.tier := agg.tier + cb.tier;
agg.tier_W_orb := agg.tier_W_orb + cb.tier_W_orb;

Print("\n=== [6,2,2,2]/[2,1]_[2,1]_[2,1]_[6,11] (M=12, 45 H) ===\n");
S_M := SymmetricGroup(12);
W_ML := BlockWreathFromPartition([6,2,2,2]);
cb := rec(norm_S := 0, norm_W := 0, ns := 0, filt := 0, trad_S_orb := 0, trad_W_orb := 0, tier := 0, tier_W_orb := 0);
H := Group([(1,2)(3,4)(5,6),(9,12),(7,9,11)(8,10,12),(7,11)(8,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(3,4)(5,6)(7,11)(8,10),(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(3,4)(5,6)(9,12),(7,11,9)(8,12,10),(7,11)(8,10),(7,8,9)(10,11,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(3,4)(5,6)(7,11)(8,10),(7,11)(8,10)(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6),(3,4),(9,12),(7,9,11)(8,10,12),(7,11)(8,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6),(3,4)(7,11)(8,10),(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6),(3,4)(9,12),(7,11,9)(8,12,10),(7,11)(8,10),(7,11,12)(8,9,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6),(3,4)(7,11)(8,10),(7,11)(8,10)(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6)(7,11)(8,10),(3,4)(9,12),(7,11,9)(8,12,10),(7,11,12)(8,9,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6)(7,11)(8,10)(9,12),(3,4)(7,11)(8,10),(7,11,9)(8,12,10),(7,8,9)(10,11,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6)(9,12),(3,4)(7,11)(8,10)(9,12),(7,11,9)(8,12,10),(7,12,11)(8,10,9)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6)(7,11)(8,10),(3,4)(7,11)(8,10)(9,12),(7,11,9)(8,12,10),(7,12,8)(9,11,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6)(9,12),(3,4)(7,11)(8,10),(7,11,9)(8,12,10),(7,12,11)(8,10,9)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6)(7,11)(8,10)(9,12),(3,4)(9,12),(7,11,9)(8,12,10),(7,8,9)(10,11,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6)(7,11)(8,10),(3,4),(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6)(9,12),(3,4),(7,11,9)(8,12,10),(7,11)(8,10),(7,8,9)(10,11,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6)(7,11)(8,10),(3,4),(7,11)(8,10)(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6)(7,11)(8,10),(3,4)(7,11)(8,10),(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6)(9,12),(3,4)(9,12),(7,11,9)(8,12,10),(7,11)(8,10),(8,9)(11,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6)(7,11)(8,10),(3,4)(7,11)(8,10),(7,11)(8,10)(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6),(3,4)(5,6),(9,12),(7,9,11)(8,10,12),(7,11)(8,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6),(3,4)(5,6)(7,11)(8,10),(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6),(3,4)(5,6)(9,12),(7,11,9)(8,12,10),(7,11)(8,10),(7,12)(9,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6),(3,4)(5,6)(7,11)(8,10),(7,11)(8,10)(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,6)(7,11)(8,10),(3,4)(5,6)(9,12),(7,11,9)(8,12,10),(7,8,9)(10,11,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2),(3,4),(5,6),(9,12),(7,9,11)(8,10,12),(7,11)(8,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2),(3,4)(7,11)(8,10),(5,6),(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2),(3,4)(9,12),(5,6),(7,11,9)(8,12,10),(7,11)(8,10),(7,8)(10,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2),(3,4)(7,11)(8,10),(5,6),(7,11)(8,10)(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(9,12),(3,4)(7,11)(8,10),(5,6),(7,11,9)(8,12,10),(7,12,11)(8,10,9)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(7,11)(8,10),(3,4)(7,11)(8,10)(9,12),(5,6),(7,11,9)(8,12,10),(7,12,8)(9,11,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(7,11)(8,10)(9,12),(3,4)(9,12),(5,6),(7,11,9)(8,12,10),(7,12,11)(8,10,9)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(7,11)(8,10),(3,4)(7,11)(8,10),(5,6),(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(9,12),(3,4)(9,12),(5,6),(7,11,9)(8,12,10),(7,11)(8,10),(7,12,11)(8,10,9)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(7,11)(8,10),(3,4)(7,11)(8,10),(5,6),(7,11)(8,10)(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(9,12),(3,4)(7,11)(8,10),(5,6)(7,11)(8,10),(7,11,9)(8,12,10),(7,11,12)(8,9,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(7,11)(8,10),(3,4)(7,11)(8,10)(9,12),(5,6)(7,11)(8,10)(9,12),(7,11,9)(8,12,10),(7,12,11)(8,10,9)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(7,11)(8,10)(9,12),(3,4)(9,12),(5,6)(9,12),(7,11,9)(8,12,10),(7,12,8)(9,11,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(7,11)(8,10)(9,12),(3,4)(7,11)(8,10),(5,6)(7,11)(8,10),(7,11,9)(8,12,10),(7,12,8)(9,11,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(7,11)(8,10),(3,4)(9,12),(5,6)(9,12),(7,11,9)(8,12,10),(7,12,8)(9,11,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(9,12),(3,4)(7,11)(8,10)(9,12),(5,6)(7,11)(8,10)(9,12),(7,11,9)(8,12,10),(7,12,8)(9,11,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(7,11)(8,10),(3,4)(7,11)(8,10),(5,6)(7,11)(8,10),(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(9,12),(3,4)(9,12),(5,6)(9,12),(7,11,9)(8,12,10),(7,11)(8,10),(7,11,12)(8,9,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(7,11)(8,10),(3,4)(7,11)(8,10),(5,6)(7,11)(8,10),(7,11)(8,10)(9,12),(7,11,9)(8,12,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(9,12),(3,4)(7,11)(8,10)(9,12),(5,6)(7,11)(8,10),(7,11,9)(8,12,10),(7,12,8)(9,11,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
Print("  TRAD-S=", cb.norm_S + cb.ns + cb.filt + cb.trad_S_orb,"ms  TRAD-W=", cb.norm_W + cb.ns + cb.filt + cb.trad_W_orb,"ms  TIERED-W=", cb.norm_W + cb.tier + cb.tier_W_orb, "ms"); 
Print(" (norm_S=", cb.norm_S, " norm_W=", cb.norm_W, " ns=", cb.ns," filt=", cb.filt, " orb_S=", cb.trad_S_orb, " orb_W=", cb.trad_W_orb," tier_enum=", cb.tier, " tier_orb=", cb.tier_W_orb, ")\n");
agg.norm_S := agg.norm_S + cb.norm_S;
agg.norm_W := agg.norm_W + cb.norm_W;
agg.ns := agg.ns + cb.ns;
agg.filt := agg.filt + cb.filt;
agg.trad_S_orb := agg.trad_S_orb + cb.trad_S_orb;
agg.trad_W_orb := agg.trad_W_orb + cb.trad_W_orb;
agg.tier := agg.tier + cb.tier;
agg.tier_W_orb := agg.tier_W_orb + cb.tier_W_orb;

Print("\n=== [6,3,3]/[3,2]_[3,2]_[6,9] (M=12, 20 H) ===\n");
S_M := SymmetricGroup(12);
W_ML := BlockWreathFromPartition([6,3,3]);
cb := rec(norm_S := 0, norm_W := 0, ns := 0, filt := 0, trad_S_orb := 0, trad_W_orb := 0, tier := 0, tier_W_orb := 0);
H := Group([(1,2,3),(1,2),(4,5,6),(4,5),(8,10,12),(7,11)(8,10),(7,10)(8,11)(9,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3),(1,2),(4,5,6),(4,5)(7,10)(8,11)(9,12),(8,12,10),(7,11)(8,10),(7,11,9)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3),(1,2),(4,5,6),(4,5)(7,11)(8,10),(8,12,10),(7,10)(8,11)(9,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3)(7,11,9)(8,10,12),(1,2)(7,12)(8,9)(10,11),(4,5,6)(7,11,9)(8,12,10),(4,5)(7,10)(8,9)(11,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3)(8,10,12),(1,2)(7,11)(8,12),(4,5,6),(4,5),(7,10)(8,11)(9,12),(7,8)(9,10)(11,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3)(8,12,10),(1,2)(7,8,11,12,9,10),(4,5,6),(4,5)(7,8)(9,12)(10,11),(7,9,11)(8,10,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3)(8,12,10),(1,2)(7,11)(10,12),(4,5,6),(4,5)(7,8)(9,12)(10,11),(7,9,11)(8,10,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3),(1,2)(7,10)(8,11)(9,12),(4,5,6),(4,5)(7,10)(8,11)(9,12),(8,12,10),(7,11)(8,10),(7,9,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3),(1,2)(7,11)(8,10),(4,5,6),(4,5)(7,11)(8,10),(8,12,10),(7,10)(8,11)(9,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3),(1,2)(7,11)(8,10),(4,5,6),(4,5)(7,10)(8,11)(9,12),(8,12,10),(7,9,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3),(1,2)(7,10)(8,11)(9,12),(4,5,6),(4,5)(7,8)(9,12)(10,11),(8,12,10),(7,9,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3),(1,2)(4,5),(4,6,5),(8,10,12),(7,11)(8,10),(7,10)(8,11)(9,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3),(1,2)(4,5)(7,10)(8,11)(9,12),(4,6,5),(8,12,10),(7,11)(8,10),(7,9,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3),(1,2)(4,5)(7,11)(8,10),(4,6,5),(8,12,10),(7,10)(8,11)(9,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3)(8,10,12),(1,2)(4,5)(7,11)(8,12),(4,6,5),(7,10)(8,11)(9,12),(7,12)(8,9)(10,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3)(8,10,12),(1,2)(4,5)(7,11)(8,10),(4,6,5)(8,10,12),(7,10)(8,11)(9,12),(7,12)(8,9)(10,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3)(4,5,6),(1,2)(4,5),(8,10,12),(7,11)(8,10),(7,10)(8,11)(9,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3)(4,5,6),(1,2)(4,5)(7,10)(8,11)(9,12),(8,12,10),(7,11)(8,10),(7,9,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3)(4,5,6),(1,2)(4,5)(7,11)(8,10),(8,12,10),(7,10)(8,11)(9,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2,3)(4,5,6)(8,10,12),(1,2)(4,5)(7,11)(8,12),(7,10)(8,11)(9,12),(7,12)(8,9)(10,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
Print("  TRAD-S=", cb.norm_S + cb.ns + cb.filt + cb.trad_S_orb,"ms  TRAD-W=", cb.norm_W + cb.ns + cb.filt + cb.trad_W_orb,"ms  TIERED-W=", cb.norm_W + cb.tier + cb.tier_W_orb, "ms"); 
Print(" (norm_S=", cb.norm_S, " norm_W=", cb.norm_W, " ns=", cb.ns," filt=", cb.filt, " orb_S=", cb.trad_S_orb, " orb_W=", cb.trad_W_orb," tier_enum=", cb.tier, " tier_orb=", cb.tier_W_orb, ")\n");
agg.norm_S := agg.norm_S + cb.norm_S;
agg.norm_W := agg.norm_W + cb.norm_W;
agg.ns := agg.ns + cb.ns;
agg.filt := agg.filt + cb.filt;
agg.trad_S_orb := agg.trad_S_orb + cb.trad_S_orb;
agg.trad_W_orb := agg.trad_W_orb + cb.trad_W_orb;
agg.tier := agg.tier + cb.tier;
agg.tier_W_orb := agg.tier_W_orb + cb.tier_W_orb;

Print("\n=== [8,2,2]/[2,1]_[2,1]_[8,38] (M=12, 5 H) ===\n");
S_M := SymmetricGroup(12);
W_ML := BlockWreathFromPartition([8,2,2]);
cb := rec(norm_S := 0, norm_W := 0, ns := 0, filt := 0, trad_S_orb := 0, trad_W_orb := 0, tier := 0, tier_W_orb := 0);
H := Group([(1,2)(3,4),(8,12),(5,12)(6,7)(8,9)(10,11),(5,6,7)(9,10,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(3,4)(8,12),(5,12)(6,7)(8,9)(10,11),(5,7,6)(9,11,10),(6,11,8)(7,12,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2),(3,4),(8,12),(5,12)(6,7)(8,9)(10,11),(5,6,7)(9,10,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2),(3,4)(8,12),(5,12)(6,7)(8,9)(10,11),(5,7,6)(9,11,10),(5,8)(6,7)(9,12)(10,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(8,12),(3,4)(8,12),(5,12)(6,7)(8,9)(10,11),(5,7,6)(9,11,10),(5,6,8)(9,10,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
Print("  TRAD-S=", cb.norm_S + cb.ns + cb.filt + cb.trad_S_orb,"ms  TRAD-W=", cb.norm_W + cb.ns + cb.filt + cb.trad_W_orb,"ms  TIERED-W=", cb.norm_W + cb.tier + cb.tier_W_orb, "ms"); 
Print(" (norm_S=", cb.norm_S, " norm_W=", cb.norm_W, " ns=", cb.ns," filt=", cb.filt, " orb_S=", cb.trad_S_orb, " orb_W=", cb.trad_W_orb," tier_enum=", cb.tier, " tier_orb=", cb.tier_W_orb, ")\n");
agg.norm_S := agg.norm_S + cb.norm_S;
agg.norm_W := agg.norm_W + cb.norm_W;
agg.ns := agg.ns + cb.ns;
agg.filt := agg.filt + cb.filt;
agg.trad_S_orb := agg.trad_S_orb + cb.trad_S_orb;
agg.trad_W_orb := agg.trad_W_orb + cb.trad_W_orb;
agg.tier := agg.tier + cb.tier;
agg.tier_W_orb := agg.tier_W_orb + cb.tier_W_orb;

Print("\n=== [8,2,2]/[2,1]_[2,1]_[8,42] (M=12, 5 H) ===\n");
S_M := SymmetricGroup(12);
W_ML := BlockWreathFromPartition([8,2,2]);
cb := rec(norm_S := 0, norm_W := 0, ns := 0, filt := 0, trad_S_orb := 0, trad_W_orb := 0, tier := 0, tier_W_orb := 0);
H := Group([(1,2)(3,4),(5,7)(6,12),(5,6,7),(5,9)(6,10)(7,11)(8,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(3,4)(5,9)(6,10)(7,11)(8,12),(5,7)(6,12),(5,7,6),(8,11,9),(5,12,7)(8,9,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2),(3,4),(5,7)(6,12),(5,6,7),(5,9)(6,10)(7,11)(8,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2),(3,4)(5,9)(6,10)(7,11)(8,12),(5,7)(6,12),(5,7,6),(8,11,9),(8,9,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(1,2)(5,9)(6,10)(7,11)(8,12),(3,4)(5,9)(6,10)(7,11)(8,12),(5,7)(6,12),(5,7,6),(8,9,10),(8,11)(9,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
Print("  TRAD-S=", cb.norm_S + cb.ns + cb.filt + cb.trad_S_orb,"ms  TRAD-W=", cb.norm_W + cb.ns + cb.filt + cb.trad_W_orb,"ms  TIERED-W=", cb.norm_W + cb.tier + cb.tier_W_orb, "ms"); 
Print(" (norm_S=", cb.norm_S, " norm_W=", cb.norm_W, " ns=", cb.ns," filt=", cb.filt, " orb_S=", cb.trad_S_orb, " orb_W=", cb.trad_W_orb," tier_enum=", cb.tier, " tier_orb=", cb.tier_W_orb, ")\n");
agg.norm_S := agg.norm_S + cb.norm_S;
agg.norm_W := agg.norm_W + cb.norm_W;
agg.ns := agg.ns + cb.ns;
agg.filt := agg.filt + cb.filt;
agg.trad_S_orb := agg.trad_S_orb + cb.trad_S_orb;
agg.trad_W_orb := agg.trad_W_orb + cb.trad_W_orb;
agg.tier := agg.tier + cb.tier;
agg.tier_W_orb := agg.tier_W_orb + cb.tier_W_orb;

Print("\n=== [8,4]/[4,4]_[8,15] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
W_ML := BlockWreathFromPartition([8,4]);
cb := rec(norm_S := 0, norm_W := 0, ns := 0, filt := 0, trad_S_orb := 0, trad_W_orb := 0, tier := 0, tier_W_orb := 0);
H := Group([(1,2,3,4,5,6,7,8),(1,5)(3,7),(1,6)(2,5)(3,4)(7,8),(9,10,11),(10,11,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
Print("  TRAD-S=", cb.norm_S + cb.ns + cb.filt + cb.trad_S_orb,"ms  TRAD-W=", cb.norm_W + cb.ns + cb.filt + cb.trad_W_orb,"ms  TIERED-W=", cb.norm_W + cb.tier + cb.tier_W_orb, "ms"); 
Print(" (norm_S=", cb.norm_S, " norm_W=", cb.norm_W, " ns=", cb.ns," filt=", cb.filt, " orb_S=", cb.trad_S_orb, " orb_W=", cb.trad_W_orb," tier_enum=", cb.tier, " tier_orb=", cb.tier_W_orb, ")\n");
agg.norm_S := agg.norm_S + cb.norm_S;
agg.norm_W := agg.norm_W + cb.norm_W;
agg.ns := agg.ns + cb.ns;
agg.filt := agg.filt + cb.filt;
agg.trad_S_orb := agg.trad_S_orb + cb.trad_S_orb;
agg.trad_W_orb := agg.trad_W_orb + cb.trad_W_orb;
agg.tier := agg.tier + cb.tier;
agg.tier_W_orb := agg.tier_W_orb + cb.tier_W_orb;

Print("\n=== [8,4]/[4,5]_[8,44] (M=12, 6 H) ===\n");
S_M := SymmetricGroup(12);
W_ML := BlockWreathFromPartition([8,4]);
cb := rec(norm_S := 0, norm_W := 0, ns := 0, filt := 0, trad_S_orb := 0, trad_W_orb := 0, tier := 0, tier_W_orb := 0);
H := Group([(4,8),(1,8)(4,5),(1,2,3,8)(4,5,6,7),(9,10,11,12),(9,10)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(4,8),(1,8)(4,5)(9,10),(1,2,3,8)(4,5,6,7)(9,10),(10,12,11),(9,12,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(4,8),(1,8)(4,5)(9,11,12,10),(1,2,3,8)(4,5,6,7)(9,12,11,10),(9,11)(10,12),(9,12)(10,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(4,8),(1,8)(4,5)(10,12),(1,2,3,8)(4,5,6,7)(9,11,10,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(4,8)(9,10),(1,8)(4,5),(1,2,3,8)(4,5,6,7),(10,12,11),(9,12,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
H := Group([(4,8)(9,10),(1,8)(4,5)(9,10),(1,2,3,8)(4,5,6,7)(9,10),(10,12,11),(9,12,11)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
Print("  TRAD-S=", cb.norm_S + cb.ns + cb.filt + cb.trad_S_orb,"ms  TRAD-W=", cb.norm_W + cb.ns + cb.filt + cb.trad_W_orb,"ms  TIERED-W=", cb.norm_W + cb.tier + cb.tier_W_orb, "ms"); 
Print(" (norm_S=", cb.norm_S, " norm_W=", cb.norm_W, " ns=", cb.ns," filt=", cb.filt, " orb_S=", cb.trad_S_orb, " orb_W=", cb.trad_W_orb," tier_enum=", cb.tier, " tier_orb=", cb.tier_W_orb, ")\n");
agg.norm_S := agg.norm_S + cb.norm_S;
agg.norm_W := agg.norm_W + cb.norm_W;
agg.ns := agg.ns + cb.ns;
agg.filt := agg.filt + cb.filt;
agg.trad_S_orb := agg.trad_S_orb + cb.trad_S_orb;
agg.trad_W_orb := agg.trad_W_orb + cb.trad_W_orb;
agg.tier := agg.tier + cb.tier;
agg.tier_W_orb := agg.tier_W_orb + cb.tier_W_orb;

Print("\n=== [9,3]/[3,1]_[9,29] (M=12, 1 H) ===\n");
S_M := SymmetricGroup(12);
W_ML := BlockWreathFromPartition([9,3]);
cb := rec(norm_S := 0, norm_W := 0, ns := 0, filt := 0, trad_S_orb := 0, trad_W_orb := 0, tier := 0, tier_W_orb := 0);
H := Group([(1,2,9),(4,5)(7,8),(1,4,7)(2,5,8)(3,6,9),(3,6)(4,7)(5,8),(10,11,12)]);
res := TimeOneH(H, S_M, W_ML);
cb.norm_S := cb.norm_S + res.norm_S;
cb.norm_W := cb.norm_W + res.norm_W;
cb.ns := cb.ns + res.ns;
cb.filt := cb.filt + res.filt;
cb.trad_S_orb := cb.trad_S_orb + res.trad_S_orb;
cb.trad_W_orb := cb.trad_W_orb + res.trad_W_orb;
cb.tier := cb.tier + res.tier;
cb.tier_W_orb := cb.tier_W_orb + res.tier_W_orb;
agg.h := agg.h + 1;
Print("  TRAD-S=", cb.norm_S + cb.ns + cb.filt + cb.trad_S_orb,"ms  TRAD-W=", cb.norm_W + cb.ns + cb.filt + cb.trad_W_orb,"ms  TIERED-W=", cb.norm_W + cb.tier + cb.tier_W_orb, "ms"); 
Print(" (norm_S=", cb.norm_S, " norm_W=", cb.norm_W, " ns=", cb.ns," filt=", cb.filt, " orb_S=", cb.trad_S_orb, " orb_W=", cb.trad_W_orb," tier_enum=", cb.tier, " tier_orb=", cb.tier_W_orb, ")\n");
agg.norm_S := agg.norm_S + cb.norm_S;
agg.norm_W := agg.norm_W + cb.norm_W;
agg.ns := agg.ns + cb.ns;
agg.filt := agg.filt + cb.filt;
agg.trad_S_orb := agg.trad_S_orb + cb.trad_S_orb;
agg.trad_W_orb := agg.trad_W_orb + cb.trad_W_orb;
agg.tier := agg.tier + cb.tier;
agg.tier_W_orb := agg.tier_W_orb + cb.tier_W_orb;

Print("\n=== AGGREGATE (across all H) ===\n");
Print("Total H:        ", agg.h, "\n");
Print("Norm in S_M:    ", agg.norm_S, "ms\n");
Print("Norm in W_ML:   ", agg.norm_W, "ms\n");
Print("NormalSubgroups:", agg.ns, "ms\n");
Print("Filter:         ", agg.filt, "ms\n");
Print("OrbitDecomp/N_S:", agg.trad_S_orb, "ms\n");
Print("OrbitDecomp/N_W:", agg.trad_W_orb, "ms\n");
Print("Tiered enum:    ", agg.tier, "ms\n");
Print("Tiered orb/N_W: ", agg.tier_W_orb, "ms\n");
Print("\n=== TOTAL TIME PER STRATEGY (all H) ===\n");
Print("TRAD-S (Norm-S + NS + filter + orb-S):    ", agg.norm_S + agg.ns + agg.filt + agg.trad_S_orb, "ms\n");
Print("TRAD-W (Norm-W + NS + filter + orb-W):    ", agg.norm_W + agg.ns + agg.filt + agg.trad_W_orb, "ms\n");
Print("TIERED-W (Norm-W + tiered + orb-W):       ", agg.norm_W + agg.tier + agg.tier_W_orb, "ms\n");
LogTo();
QUIT;
