USE_TF_DATABASE := true;;
LogTo("/cygdrive/c/Users/jeffr/Downloads/Lifting/debug_655_v5.log");
Read("/cygdrive/c/Users/jeffr/Downloads/Lifting/lifting_method_fast_v2.g");
LIFT_CACHE.("15") := 159129;
COMBO_OUTPUT_DIR := "/cygdrive/c/Users/jeffr/Downloads/Lifting/parallel_sn/16/[6,5,5]";
fpf := FindFPFClassesForPartition(16, [6,5,5]);
Print("\n");
Print("RESULT_655=", Length(fpf), "\n");
Print("TF_STATS=", TF_LOOKUP_STATS, "\n");
LogTo();
QUIT;
