"""
generate_transitive_db.py - Generate transitive subgroups database

This script generates the precomputed transitive subgroups database
by running GAP to enumerate conjugacy class representatives of subgroups
for each transitive group.
"""

import subprocess
import os
import sys
import time

def generate_transitive_db_for_degree(n):
    """Generate transitive subgroups database for degree n."""

    gap_commands = f'''
# Generate transitive subgroups database for degree {n}

DATABASE_PATH := "C:/Users/jeffr/Downloads/Lifting/database/";
filename := Concatenation(DATABASE_PATH, "transitive_subgroups/degree_{n:02d}.g");

nrGroups := NrTransitiveGroups({n});
Print("Degree {n}: ", nrGroups, " transitive groups\\n");

# Build the data structure
TRANS_DATA := rec();
TRANS_DATA.("{n}") := rec();

for k in [1..nrGroups] do
    T := TransitiveGroup({n}, k);
    Print("  T(", {n}, ",", k, "): |G| = ", Size(T), " ... ");

    # Get conjugacy class representatives
    classes := ConjugacyClassesSubgroups(T);
    reps := List(classes, Representative);

    # Store as generator lists
    genSetsList := [];
    for H in reps do
        gens := GeneratorsOfGroup(H);
        genLists := [];
        for g in gens do
            if g = () then
                Add(genLists, []);
            else
                Add(genLists, ListPerm(g, NrMovedPoints(T)));
            fi;
        od;
        Add(genSetsList, genLists);
    od;

    TRANS_DATA.("{n}").(String(k)) := genSetsList;
    Print(Length(reps), " subgroups\\n");
od;

# Write to file
output := "";
output := Concatenation(output, "###############################################################################\\n");
output := Concatenation(output, "# degree_{n:02d}.g - Precomputed subgroups for transitive groups of degree {n}\\n");
output := Concatenation(output, "# Auto-generated by generate_transitive_db.py\\n");
output := Concatenation(output, "###############################################################################\\n\\n");

# Start the TRANSITIVE_SUBGROUPS record if not already started
output := Concatenation(output, "if not IsBound(TRANSITIVE_SUBGROUPS) then\\n");
output := Concatenation(output, "    TRANSITIVE_SUBGROUPS := rec();\\n");
output := Concatenation(output, "fi;\\n\\n");

output := Concatenation(output, "TRANSITIVE_SUBGROUPS.(\\"{n}\\") := rec(\\n");

for k in [1..nrGroups] do
    data := TRANS_DATA.("{n}").(String(k));
    output := Concatenation(output, "  (\\"", String(k), "\\") := [\\n");

    for j in [1..Length(data)] do
        genSets := data[j];
        output := Concatenation(output, "    ", String(genSets));
        if j < Length(data) then
            output := Concatenation(output, ",");
        fi;
        output := Concatenation(output, "\\n");
    od;

    output := Concatenation(output, "  ]");
    if k < nrGroups then
        output := Concatenation(output, ",");
    fi;
    output := Concatenation(output, "\\n");
od;

output := Concatenation(output, ");\\n");

PrintTo(filename, output);
Print("Wrote to ", filename, "\\n");

QUIT;
'''

    # Write commands to temp file
    with open(r"C:\Users\jeffr\Downloads\Lifting\temp_trans_gen.g", "w") as f:
        f.write(gap_commands)

    # GAP environment setup
    gap_runtime = r"C:\Program Files\GAP-4.15.1\runtime"
    bash_exe = r"C:\Program Files\GAP-4.15.1\runtime\bin\bash.exe"
    script_path = "/cygdrive/c/Users/jeffr/Downloads/Lifting/temp_trans_gen.g"

    env = os.environ.copy()
    env['PATH'] = r"C:\Program Files\GAP-4.15.1\runtime\bin;" + env.get('PATH', '')
    env['CYGWIN'] = 'nodosfilewarning'

    print(f"\nGenerating transitive subgroups for degree {n}...")
    print("-" * 60)

    start = time.time()

    # Run GAP via Cygwin bash
    process = subprocess.Popen(
        [bash_exe, "--login", "-c",
         f'cd "/cygdrive/c/Program Files/GAP-4.15.1/runtime/opt/gap-4.15.1" && ./gap.exe -q "{script_path}"'],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        env=env,
        cwd=gap_runtime
    )

    # Use appropriate timeout based on degree
    timeout = 60 * (2 ** max(0, n - 5))  # Exponentially increase timeout
    timeout = min(timeout, 3600)  # Cap at 1 hour

    try:
        stdout, stderr = process.communicate(timeout=timeout)
        elapsed = time.time() - start
        print(stdout)
        if stderr and "Syntax warning" not in stderr:
            print("STDERR:", stderr)
        print(f"Completed in {elapsed:.1f}s")
        return True
    except subprocess.TimeoutExpired:
        process.kill()
        print(f"TIMEOUT after {timeout}s")
        return False

    # Cleanup
    try:
        os.remove(r"C:\Users\jeffr\Downloads\Lifting\temp_trans_gen.g")
    except:
        pass


def main():
    print("=" * 60)
    print("Generating Transitive Subgroups Database")
    print("=" * 60)

    # Generate for degrees 2-8 first (fast)
    for n in range(2, 9):
        success = generate_transitive_db_for_degree(n)
        if not success:
            print(f"Failed for degree {n}, stopping")
            break

    # Cleanup
    try:
        os.remove(r"C:\Users\jeffr\Downloads\Lifting\temp_trans_gen.g")
    except:
        pass

    print("\n" + "=" * 60)
    print("Done!")
    print("=" * 60)


if __name__ == "__main__":
    main()
