"""
Investigation: Why [9,8] partition of S17 is stuck at combo 653

FINDING: The stuck combo is NOT #654 but #653 = TG(9,14) x TG(8,3)

Evidence from worker logs (worker_8.log, worker_17.log, worker_22.log):
All three independent runs get stuck at exactly the same point.
"""

# === COMBO ITERATION ORDER ===
# Partition [9,8]: depth 1 iterates TG(9,j) for j=1..34, depth 2 iterates TG(8,k) for k=1..50
# Since 9 != 8, no skip logic applies. Total combos = 34 * 50 = 1700
# Combo number = (j-1)*50 + k

# Checkpoint has 652 completed combos:
# j=1..13 (all 50 TG(8,k) each) = 650 combos
# j=14: k=1 (combo 651), k=2 (combo 652)
# Next: j=14, k=3 = combo 653

print("=== COMBO IDENTIFICATION ===")
print("Combo 651: TG(9,14) x TG(8,1) - cache key [ [ 8, 1 ], [ 9, 14 ] ]")
print("Combo 652: TG(9,14) x TG(8,2) - cache key [ [ 8, 2 ], [ 9, 14 ] ]")
print("Combo 653: TG(9,14) x TG(8,3) - cache key [ [ 8, 3 ], [ 9, 14 ] ]  <-- STUCK HERE")
print("Combo 654: TG(9,14) x TG(8,4) - cache key [ [ 8, 4 ], [ 9, 14 ] ]")
print()

# === EVIDENCE FROM WORKER LOGS ===
print("=== EVIDENCE FROM WORKER LOGS ===")
print()
print("worker_8.log (original run) ends at line 4655:")
print('  >> combo [[ [ 8, 3 ], [ 9, 14 ] ]] factors=[ [ 9, 14 ], [ 8, 3 ] ] |P|=576')
print('  Goursat fast path: |T1|=72 |T2|=8, 7x16 normal pairs -> 64 FPF subdirects (94ms)')
print("  [LOG ENDS - no combo completion message]")
print()
print("worker_17.log (resumed run) ends at line 956:")
print('  >> combo [[ [ 8, 3 ], [ 9, 14 ] ]] factors=[ [ 9, 14 ], [ 8, 3 ] ] |P|=576')
print('  Goursat fast path: |T1|=72 |T2|=8, 7x16 normal pairs -> 64 FPF subdirects (141ms)')
print("  [LOG ENDS - no combo completion message]")
print()
print("worker_22.log (another resumed run) ends at line 956:")
print('  >> combo [[ [ 8, 3 ], [ 9, 14 ] ]] factors=[ [ 9, 14 ], [ 8, 3 ] ] |P|=576')
print('  Goursat fast path: |T1|=72 |T2|=8, 7x16 normal pairs -> 64 FPF subdirects (109ms)')
print("  [LOG ENDS - no combo completion message]")
print()
print("ALL THREE runs stop at EXACTLY the same point: after GoursatFPFSubdirects")
print("returns 64 FPF subdirects, but before incrementalDedup completes.")
print()

# === WHAT HAPPENS AFTER GOURSAT RETURNS ===
print("=== CODE PATH AFTER GOURSAT RETURNS 64 RESULTS ===")
print()
print("1. GoursatFPFSubdirects returns 64 FPF subdirects (fast: ~100ms)")
print("2. FindFPFClassesByLifting returns these 64 results")
print("3. Back in FindFPFClassesForPartition:")
print("   FPF_SUBDIRECT_CACHE.(cacheKey) := _liftResult;   -- instant")
print("   incrementalDedup(_liftResult);                    -- STUCK HERE")
print()
print("incrementalDedup calls AddIfNotConjugate for each of 64 results,")
print("which calls RepresentativeAction(N, H, rep) for groups in the invariant bucket.")
print()

# === WHY incrementalDedup HANGS ===
print("=== ROOT CAUSE: incrementalDedup on 64 Goursat results ===")
print()
print("N = BuildConjugacyTestGroup(17, [9,8]) = S_9 x S_8")
print("|N| = 9! * 8! = 362880 * 40320 = 14,631,321,600 (~14.6 billion)")
print()
print("invFunc = CheapSubgroupInvariant (partition has all distinct parts)")
print("Invariant = [Size, DerivedLength, |Center|, |DerivedSubgroup|, Exponent, orbit_lengths]")
print()
print("Problem: The 64 Goursat results from TG(9,14) x TG(8,3) likely share")
print("very similar invariants (all are subdirects of a 576-element group on 17 pts,")
print("all FPF with orbit structure [9,8]). Many may have:")
print("  - Same size (e.g., 72, 144, 288)")
print("  - Same derived length")
print("  - Same center/derived sizes")
print("  - Same exponent")
print("  - Same orbit lengths = [8, 9]")
print()
print("If K of the 64 results share the same invariant, dedup is O(K^2/2)")
print("RepresentativeAction calls, each potentially very expensive because")
print("|N| = 14.6 billion requires deep backtrack search.")
print()

# === COMPARISON WITH OTHER COMBOS ===
print("=== COMPARISON: Why [8,3] [9,13] works but [8,3] [9,14] doesn't ===")
print()
print("TG(9,13): |T1| = 54, 7 normals")
print("TG(9,14): |T1| = 72, 7 normals")
print()
print("[8,3] x [9,13]: 7x16 normal pairs -> 8 FPF subdirects  (completed in ~1s)")
print("[8,3] x [9,14]: 7x16 normal pairs -> 64 FPF subdirects (STUCK)")
print()
print("The 8x increase in FPF results is the key difference.")
print("8 results -> O(8^2/2) = 32 RA calls -> ~32s")
print("64 results -> O(64^2/2) = 2048 RA calls -> potentially hours")
print()

# === GROUP IDENTITIES ===
print("=== GROUP IDENTITIES (from log data) ===")
print()
print("TG(9,14): order 72 = 2^3 * 3^2, degree 9")
print("  Likely AGL(1,9) = F_9 : F_9* (affine group of the field with 9 elements)")
print("  Point stabilizer: order 72/9 = 8 = F_9*")
print("  7 normal subgroups")
print()
print("TG(8,3): order 8, degree 8 (regular representation)")
print("  Has 16 normal subgroups -> ALL subgroups are normal -> ABELIAN")
print("  Only abelian group of order 8 with 16 subgroups is C_2^3")
print("  (C_8 has 4 subgroups, C_4 x C_2 has 6+2=6 subgroups)")
print("  Wait: C_2^3 has 1 + 7 + 7 + 1 = 16 subgroups, all normal. YES.")
print("  TG(8,3) = C_2^3 (elementary abelian 2-group, regular representation)")
print()
print("  Note: TG(8,1) has 4 normals -> C_8")
print("        TG(8,2) has 8 normals -> probably C_4 x C_2 (has 6 subgroups)")
print("        Wait, log says 7x8 for [8,2][9,14], so TG(8,2) has 8 normals.")
print("        Actually the 7 is for TG(9,14), 8 is for TG(8,2).")
print("        C_4 x C_2 has subgroups: {e}, C_2 (3 copies), C_4, C_2^2, C_4xC_2 = 7")
print("        No wait: C_4xC_2 subgroups: {e}, <a^2>, <b>, <a^2 b> (3 order-2 subgroups),")
print("        <a> (order 4), <a^2, b> ≅ C_2^2, and the whole group. That's 7 subgroups.")
print("        But log says 8 normals for TG(8,2). Hmm.")
print("        Actually {e} and G count. Let me recount:")
print("        {e}, <a^2>, <b>, <a^2 b> = 3 of order 2, <a> of order 4,")
print("        <a^2, b> ≅ V_4, and G itself. That's 7. But log says 8.")
print("        Maybe I miscounted or TG(8,2) is different.")
print()

# === PROPOSED SOLUTIONS ===
print("=== PROPOSED SOLUTIONS ===")
print()
print("1. IMPROVE INVARIANT DISCRIMINATION")
print("   CheapSubgroupInvariant is too weak for this case.")
print("   Use CheapSubgroupInvariantFull or add per-block TransitiveIdentification")
print("   to the invariant. This would separate the 64 results into smaller buckets,")
print("   dramatically reducing the number of RA calls.")
print()
print("2. LIMIT GOURSAT OUTPUT SIZE")
print("   If Goursat produces > N results (e.g., N=32), the incremental dedup")
print("   becomes O(N^2). Could batch-dedup the Goursat results using")
print("   RepresentativeAction(P, ...) first (much cheaper since |P| = 576 << |N|),")
print("   then only do N-dedup on the P-class representatives.")
print()
print("3. USE P-DEDUP BEFORE N-DEDUP")
print("   The 64 Goursat results are P-class representatives. But they may be")
print("   N-conjugate (N = S_9 x S_8 > P). So many of the 64 are duplicates under N.")
print("   First dedup under P (cheap, |P|=576) to verify they're truly P-distinct,")
print("   then dedup under N (expensive). This won't help if they're ALL P-distinct")
print("   but N-conjugate, which requires the expensive RA calls.")
print()
print("4. BATCH DEDUP WITH P-ORBITS (BEST)")
print("   For 2-factor partitions, N = S_d1 x S_d2. The N-conjugacy classes of")
print("   subgroups of P correspond to orbits of N/P on P-conjugacy classes.")
print("   Compute N-orbit on the 64 P-class reps using RepresentativeAction(P,...)")
print("   to match images, instead of RepresentativeAction(N,...) directly.")
print("   This turns 2048 expensive RA(N,...) calls into a manageable number of")
print("   cheaper RA(P,...) calls.")
print()
print("5. SKIP-AHEAD HEURISTIC")
print("   Since all previous combos with TG(8,3) for j<14 completed quickly,")
print("   and the issue is specifically with TG(9,14) x TG(8,3) producing 64 results,")
print("   a short-term workaround would be to increase the Goursat output threshold")
print("   and fall back to lifting when Goursat produces too many results.")
print("   But this is a band-aid, not a fix.")
