# prototype_stage_b.g
#
# Stage B: Linear orbits on D_8 (= SmallGroup(8,3)) kernels via the two-
# layer Frattini decomposition.
#
#   Outer layer: V_4-kernel L of H.  Stage A enumerates these.
#   Inner layer: index-2 subgroups K of L containing [H,L]·L^2 form the
#               candidates; filter to those with H/K ≅ D_8 (drops Q_8
#               and V_4 × C_2 quotients).
#   Inner orbits: Stab_NH(L) acts linearly on B = L / [H,L]·L^2 via
#                 ρ_L: Stab_NH(L) → GL(B); orbits on codim-1 subspaces
#                 of B give Stab_NH(L)-orbits of D_8-kernels.
#
# Same right-action convention (inverse conjugation, n^-1 * x * n) as
# Stage A — see comments in prototype_stage_a.g.
#
# Exports:
#   RelFrattiniData(H, L, p) -> rec(NHL, hom_to_B, B, pcgs, d)
#   LinearOrbitRecsD8(H, N_H) -> [ rec(K_H_gens, Stab_NH_KH_gens,
#                                       qid, qsize) ]
#   CompareWithNormalSubgroups(H, N_H) for ground-truth parity check.

if not IsBound(LinearOrbitRecsCpa) then
    Print("Need Stage A loaded; reading prototype_stage_a.g\n");
    Read("C:/Users/jeffr/Downloads/Lifting/prototype_stage_a.g");
fi;


# B = L / ([H,L] · L^p) — the relative Frattini quotient of L w.r.t. H.
# Returns rec(NHL := [H,L]·L^p, hom_to_B, B, pcgs, d).
RelFrattiniData := function(H, L, p)
    local L_squares, NHL, hom_to_B, B, pcgs_B, dB;
    # [H, L] · L^p, where L^p = subgroup generated by p-th powers of
    # L's generators (sufficient since L^p is normal; in particular
    # contained in any normal K with L/K elementary abelian of exp p).
    L_squares := SubgroupNC(L, List(GeneratorsOfGroup(L), g -> g^p));
    NHL := ClosureGroup(CommutatorSubgroup(H, L), L_squares);
    hom_to_B := NaturalHomomorphismByNormalSubgroup(L, NHL);
    B := Image(hom_to_B);
    if Size(B) = 1 then
        return rec(NHL := NHL, hom_to_B := hom_to_B, B := B,
                   pcgs := [], d := 0);
    fi;
    pcgs_B := Pcgs(B);
    dB := Length(pcgs_B);
    return rec(NHL := NHL, hom_to_B := hom_to_B, B := B,
               pcgs := pcgs_B, d := dB);
end;


# Matrix representation of stab_NH_L (or any subgroup of N_H stabilizing
# L) acting on B = L/NHL via conjugation.  Right-action convention.
StabActionOnB := function(S, hom_to_B, pcgs_B, d, p)
    local gens, mats, n, M, j, b, l, nl, exp;
    if d = 0 then return rec(mats := []); fi;
    gens := GeneratorsOfGroup(S);
    mats := [];
    for n in gens do
        M := [];
        for j in [1..d] do
            b := pcgs_B[j];
            l := PreImagesRepresentative(hom_to_B, b);
            nl := n^-1 * l * n;
            exp := ExponentsOfPcElement(pcgs_B, Image(hom_to_B, nl));
            Add(M, exp * One(GF(p)));
        od;
        Add(mats, M);
    od;
    return rec(mats := mats);
end;


# Stage B main: enumerate D_8-kernel orbits of N_H acting on H.
LinearOrbitRecsD8 := function(H, N_H)
    local recs, v4_recs, v4_rec, L, S, BHL, NHL_gens, gens_S, action,
          mats, V, all_hps, Sgrp, lift_act_B, safe_act_subsp_b, d8_canonicals,
          orbits, qid, qsize, hp, K_gens_in_L, K, k_quot_id, orb,
          W_rep, K_gens, stab_S, v, b_elem;
    qsize := 8;
    qid := [8, 0, [8, 3]];   # D_8 SafeId
    recs := [];

    v4_recs := LinearOrbitRecsCpa(H, N_H, 2, 2);

    for v4_rec in v4_recs do
        L := SubgroupNC(H, v4_rec.K_H_gens);
        S := Subgroup(N_H, v4_rec.Stab_NH_KH_gens);
        BHL := RelFrattiniData(H, L, 2);
        if BHL.d = 0 then continue; fi;
        NHL_gens := GeneratorsOfGroup(BHL.NHL);
        V := GF(2) ^ BHL.d;

        # Canonical forms of all codim-1 subspaces (hyperplanes) of B.
        all_hps := List(Subspaces(V, BHL.d - 1), function(s)
            local bv;
            bv := BasisVectors(Basis(s));
            if Length(bv) = 0 then return []; fi;
            return TriangulizedMat(List(bv, ShallowCopy));
        end);

        # Pre-filter to hyperplanes whose lift K gives H/K ≅ D_8.
        d8_canonicals := [];
        for hp in all_hps do
            K_gens_in_L := [];
            for v in hp do
                b_elem := Product(List([1..BHL.d],
                    i -> BHL.pcgs[i] ^ IntFFE(v[i])));
                Add(K_gens_in_L, PreImagesRepresentative(BHL.hom_to_B, b_elem));
            od;
            K := SubgroupNC(H, Concatenation(NHL_gens, K_gens_in_L));
            k_quot_id := IdGroup(FactorGroupNC(H, K));
            if k_quot_id = [8, 3] then
                Add(d8_canonicals, hp);
            fi;
        od;
        if Length(d8_canonicals) = 0 then continue; fi;

        # Compute S action on B; build matrix group; compute orbits.
        action := StabActionOnB(S, BHL.hom_to_B, BHL.pcgs, BHL.d, 2);
        mats := action.mats;

        lift_act_B := function(W, n)
            local Mn, j, b, l, nl, exp;
            if BHL.d = 0 then return W; fi;
            Mn := [];
            for j in [1..BHL.d] do
                b := BHL.pcgs[j];
                l := PreImagesRepresentative(BHL.hom_to_B, b);
                nl := n^-1 * l * n;
                exp := ExponentsOfPcElement(BHL.pcgs, Image(BHL.hom_to_B, nl));
                Add(Mn, exp * One(GF(2)));
            od;
            if Length(W) = 0 then return W; fi;
            return OnSubspacesByCanonicalBasis(W, Mn);
        end;

        if Length(mats) = 0 then
            # S trivial — each D_8-hyperplane its own orbit, Stab = S.
            for W_rep in d8_canonicals do
                K_gens_in_L := [];
                for v in W_rep do
                    b_elem := Product(List([1..BHL.d],
                        i -> BHL.pcgs[i] ^ IntFFE(v[i])));
                    Add(K_gens_in_L,
                        PreImagesRepresentative(BHL.hom_to_B, b_elem));
                od;
                K := SubgroupNC(H, Concatenation(NHL_gens, K_gens_in_L));
                Add(recs, rec(
                    K_H_gens := GeneratorsOfGroup(K),
                    Stab_NH_KH_gens := GeneratorsOfGroup(S),
                    # |Stab| = |S| since S acts trivially -- avoids fresh
                    # Schreier-Sims on Stab in the labelled-subgroup harvest.
                    Stab_NH_KH_size := Size(S),
                    qid := qid,
                    qsize := qsize));
            od;
            continue;
        fi;

        Sgrp := Group(mats);
        # Wrapper around OnSubspacesByCanonicalBasis that handles the empty-
        # subspace case (codim = dim B), where GAP's builtin errors.
        safe_act_subsp_b := function(W, mat)
            if Length(W) = 0 then return W; fi;
            return OnSubspacesByCanonicalBasis(W, mat);
        end;
        # Orbits restricted to d8_canonicals — note OrbitsDomain over
        # d8_canonicals only is correct because S preserves the filter
        # (Stab_NH(L) maps D_8-kernels of H to D_8-kernels of H).
        orbits := OrbitsDomain(Sgrp, d8_canonicals, safe_act_subsp_b);

        for orb in orbits do
            W_rep := orb[1];
            K_gens_in_L := [];
            for v in W_rep do
                b_elem := Product(List([1..BHL.d],
                    i -> BHL.pcgs[i] ^ IntFFE(v[i])));
                Add(K_gens_in_L,
                    PreImagesRepresentative(BHL.hom_to_B, b_elem));
            od;
            K := SubgroupNC(H, Concatenation(NHL_gens, K_gens_in_L));
            stab_S := Stabilizer(S, W_rep, lift_act_B);
            Add(recs, rec(
                K_H_gens := GeneratorsOfGroup(K),
                Stab_NH_KH_gens := GeneratorsOfGroup(stab_S),
                # |Stab| = |S| / |orbit| -- free from the orbit we just
                # enumerated; avoids Schreier-Sims on Stab in the harvest.
                Stab_NH_KH_size := Size(S) / Length(orb),
                qid := qid,
                qsize := qsize));
        od;
    od;
    return recs;
end;


# Ground-truth: enumerate D_8-kernels via NormalSubgroups(H), group
# under N_H-conjugation.  Slow but reliable for small H.
GroundTruthD8Orbits := function(H, N_H)
    local target_id, NS, d8_kernels, K, orbits, K0, orb, found, K1,
          n, conj_K, stab;
    target_id := [8, 3];
    NS := NormalSubgroups(H);
    d8_kernels := Filtered(NS, K ->
        Size(H) / Size(K) = 8 and IdGroup(FactorGroupNC(H, K)) = target_id);
    # Bucket by N_H-conjugation.
    orbits := [];
    for K0 in d8_kernels do
        found := false;
        for orb in orbits do
            for K1 in orb do
                if RepresentativeAction(N_H, K0, K1, OnPoints) <> fail then
                    Add(orb, K0);
                    found := true;
                    break;
                fi;
            od;
            if found then break; fi;
        od;
        if not found then
            Add(orbits, [K0]);
        fi;
    od;
    # Pack as records.
    return List(orbits, function(orb)
        local rep, stab;
        rep := orb[1];
        stab := Stabilizer(N_H, rep, OnPoints);
        return rec(
            K_H_gens := GeneratorsOfGroup(rep),
            Stab_NH_KH_gens := GeneratorsOfGroup(stab),
            qid := [8, 0, [8, 3]],
            qsize := 8);
    end);
end;


# Parity scaffold for Stage B.
CompareD8WithGroundTruth := function(H, N_H)
    local linear, truth, sizes_l, sizes_t;
    linear := LinearOrbitRecsD8(H, N_H);
    truth := GroundTruthD8Orbits(H, N_H);
    sizes_l := SortedList(List(linear,
        r -> Size(Group(r.Stab_NH_KH_gens))));
    sizes_t := SortedList(List(truth,
        r -> Size(Group(r.Stab_NH_KH_gens))));
    return rec(
        ok := (Length(sizes_l) = Length(sizes_t)) and (sizes_l = sizes_t),
        n_linear := Length(linear),
        n_truth := Length(truth),
        stab_sizes_linear := sizes_l,
        stab_sizes_truth := sizes_t);
end;

# Helper: InducedAutoGens duplicated here to avoid taking a dependency on the
# caller's namespace (wreath worker defines it, but standalone consumers may not).
if not IsBound(_StageB_InducedAutoGens) then
    _StageB_InducedAutoGens := function(stab, G, hom)
        return List(GeneratorsOfGroup(stab),
            s -> InducedAutomorphism(hom, ConjugatorAutomorphism(G, s)));
    end;
fi;


# Rich variant of LinearOrbitRecsD8: adds hom (H -> Q) and A_gens to each
# record.  For D_8 there is no clean two-layer factorization of H -> H/K
# (the inner C_2 = L/K doesn't extend to an H -> C_2 map), so we fall back
# to NaturalHomomorphismByNormalSubgroup(H, K) for the hom and InducedAutoGens
# for A_gens.  Bundled here so the wreath worker sees a uniform Rich API
# across qids.  Caller-visible savings come from eliminating the per-K hom
# rebuild it would otherwise do AFTER the K_H gens are returned.
LinearOrbitRecsD8Rich := function(H, N_H)
    local recs_plain, recs, r, K, hom, Q, stab_NH, A_gens;
    recs_plain := LinearOrbitRecsD8(H, N_H);
    recs := [];
    for r in recs_plain do
        K := SubgroupNC(H, r.K_H_gens);
        hom := NaturalHomomorphismByNormalSubgroup(H, K);
        Q := Range(hom);
        stab_NH := SubgroupNC(N_H, r.Stab_NH_KH_gens);
        A_gens := _StageB_InducedAutoGens(stab_NH, H, hom);
        Add(recs, rec(
            K_H_gens := r.K_H_gens,
            Stab_NH_KH_gens := r.Stab_NH_KH_gens,
            # Carry forward the plain variant's Stab_NH_KH_size if present
            # (avoids re-computing Size(stab_NH) here).
            Stab_NH_KH_size := r.Stab_NH_KH_size,
            qid := r.qid,
            qsize := r.qsize,
            hom := hom,
            Q := Q,
            A_gens := A_gens));
    od;
    return recs;
end;


Print("prototype_stage_b.g loaded.\n");
Print("  RelFrattiniData(H, L, p)\n");
Print("  LinearOrbitRecsD8(H, N_H)\n");
Print("  LinearOrbitRecsD8Rich(H, N_H)\n");
Print("  GroundTruthD8Orbits(H, N_H)\n");
Print("  CompareD8WithGroundTruth(H, N_H)\n");
