# prototype_stage_a.g
#
# Stage A: Linear orbits on C_p^a kernels via H / Phi_p(H).
#
# Replaces, for elementary abelian quotients only, the production code's
#   Orbits(N_H, kernels, ConjAction) + Stabilizer(N_H, K, ConjAction)
# (which calls RA on subgroup objects) with a matrix-group orbit on
# (dim A - a)-dimensional subspaces of A = H / Phi_p(H).
#
# Not yet wired into production. Goals of this prototype:
#   1. Verify orbit count and stabilizer-order parity vs cached records
#      across many H entries.
#   2. Establish a correctness scaffold before considering D_8 (Stage B)
#      or general solvable (Stage D).
#
# Exports:
#   ElemAbPQuotient(H, p)       -> rec(Phi, A, hom, pcgs, d)
#   NHActionOnElemAb(N_H, A_data, p) -> rec(mats)
#   LinearOrbitRecsCpa(H, N_H, p, a) -> [ rec(K_H_gens, Stab_NH_KH_gens,
#                                              qid, qsize) ]
#   CompareWithCached(H, N_H, cached_orbits, p, a)
#       -> rec(ok, n_linear, n_cached, stab_sizes_linear, stab_sizes_cached)


# ---- Phi_p(H) and the max elementary-abelian p-quotient ----
# Phi_p(H) = H' * H^p.  Returns the quotient H/Phi_p(H) as a Pc group
# along with the homomorphism, pcgs, and F_p-dimension.
ElemAbPQuotient := function(H, p)
    local D, hom_d, D_quot, p_pow_sub, Phi, hom_full, A, pcgs, d;
    D := DerivedSubgroup(H);
    hom_d := NaturalHomomorphismByNormalSubgroup(H, D);
    D_quot := Image(hom_d);   # H/H', abelian
    if Size(D_quot) = 1 then
        # H is perfect — no non-trivial abelian (hence no C_p^a) quotient.
        return rec(Phi := H, A := TrivialGroup(IsPcGroup),
                   hom := fail, pcgs := [], d := 0);
    fi;
    # p-th powers in the abelian quotient form a (normal) subgroup
    # generated by p-th powers of generators.
    p_pow_sub := SubgroupNC(D_quot,
                            List(GeneratorsOfGroup(D_quot), x -> x^p));
    Phi := PreImage(hom_d, p_pow_sub);   # = H' * H^p, normal in H
    hom_full := NaturalHomomorphismByNormalSubgroup(H, Phi);
    A := Image(hom_full);
    if Size(A) = 1 then
        return rec(Phi := Phi, A := A, hom := hom_full, pcgs := [], d := 0);
    fi;
    pcgs := Pcgs(A);
    d := Length(pcgs);
    return rec(Phi := Phi, A := A, hom := hom_full, pcgs := pcgs, d := d);
end;


# ---- rho: N_H -> GL(A) as a matrix group over GF(p) ----
# Returns matrices for each generator of N_H.  Note: rho is well-defined
# because H is normal in N_H (it's the normalizer), so conjugation by
# n in N_H preserves H, and the induced action on A = H/Phi_p(H) is linear.
#
# Convention: M_g[i,:] = exponents of (g^-1 * pcgs[i] * g) in A.  This
# choice (inverse conjugation, NOT g*x*g^-1) makes rho a GAP-compatible
# right action: M_{gh} = M_g * M_h.  The natural-looking g*x*g^-1
# convention gives M_{gh} = M_h * M_g (an anti-homomorphism), which then
# silently breaks Stabilizer's Schreier-Sims base-point walk and inflates
# computed stabilizers — orbits would still come out right but stabilizer
# computation would not.
NHActionOnElemAb := function(N_H, A_data, p)
    local gens, mats, n, M, j, a, h, nh, exp;
    if A_data.d = 0 then
        return rec(mats := []);
    fi;
    gens := GeneratorsOfGroup(N_H);
    mats := [];
    for n in gens do
        M := [];
        for j in [1..A_data.d] do
            a := A_data.pcgs[j];
            h := PreImagesRepresentative(A_data.hom, a);
            nh := n^-1 * h * n;   # see comment: right-action convention
            exp := ExponentsOfPcElement(A_data.pcgs, Image(A_data.hom, nh));
            Add(M, exp * One(GF(p)));
        od;
        Add(mats, M);
    od;
    return rec(mats := mats);
end;


# ---- Stage A: N_H-orbit records for C_p^a kernels ----
# Production-ready output: Stab_NH_KH_gens is an actual list of generators
# of Stab_NH(K) in N_H, matching the production rec shape.
LinearOrbitRecsCpa := function(H, N_H, p, a)
    local A_data, action, gens_NH, mats, Mgrp, V, all_subs, safe_act_subsp,
          orbits, qid, qsize, recs, Phi_gens, orb, U_rep, U_gens, v,
          a_elem, K, C_p_to_a, lift_act, stab_NH;
    A_data := ElemAbPQuotient(H, p);
    if a < 1 then return []; fi;
    if a > A_data.d then return []; fi;

    qsize := p^a;
    C_p_to_a := AbelianGroup(IsPcGroup, List([1..a], i -> p));
    # qid format mirrors production SafeId-style: [qsize, 0, [smallgrp_size, smallgrp_id]]
    qid := [qsize, 0, IdGroup(C_p_to_a)];
    Phi_gens := GeneratorsOfGroup(A_data.Phi);

    action := NHActionOnElemAb(N_H, A_data, p);
    mats := action.mats;
    gens_NH := GeneratorsOfGroup(N_H);

    V := GF(p) ^ A_data.d;
    # Pre-compute canonical-basis matrices for each (codim-a) subspace.
    # Zero subspace -> empty list [].  TriangulizedMat *is* canonical
    # (reduced row-echelon form) for matrices over a field — verified.
    all_subs := List(Subspaces(V, A_data.d - a), function(s)
        local bv;
        bv := BasisVectors(Basis(s));
        if Length(bv) = 0 then return []; fi;
        return TriangulizedMat(List(bv, ShallowCopy));
    end);

    # Lifted action on canonical-basis matrices: applies conjugation via
    # H/Phi to obtain matrix M for n, then TriangulizedMat(U * M).
    lift_act := function(U, n)
        local M, j, a, h, nh, exp;
        if A_data.d = 0 then return U; fi;
        M := [];
        for j in [1..A_data.d] do
            a := A_data.pcgs[j];
            h := PreImagesRepresentative(A_data.hom, a);
            nh := n^-1 * h * n;   # see comment: right-action convention
            exp := ExponentsOfPcElement(A_data.pcgs, Image(A_data.hom, nh));
            Add(M, exp * One(GF(p)));
        od;
        if Length(U) = 0 then return U; fi;
        return OnSubspacesByCanonicalBasis(U, M);
    end;

    if Length(mats) = 0 then
        # N_H trivial — each subspace its own orbit, Stab = N_H.
        recs := [];
        for U_rep in all_subs do
            U_gens := List(U_rep,
                v -> PreImagesRepresentative(A_data.hom,
                    Product(List([1..A_data.d],
                        i -> A_data.pcgs[i]^IntFFE(v[i])))));
            K := SubgroupNC(H, Concatenation(Phi_gens, U_gens));
            Add(recs, rec(
                K_H_gens := GeneratorsOfGroup(K),
                Stab_NH_KH_gens := gens_NH,
                # |Stab| = |N_H| since N_H acts trivially -- avoids fresh
                # Schreier-Sims on Stab in the labelled-subgroup harvest.
                Stab_NH_KH_size := Size(N_H),
                qid := qid,
                qsize := qsize));
        od;
        return recs;
    fi;

    Mgrp := Group(mats);
    # See LinearOrbitRecsCpaRich for why we need this wrapper: GAP's
    # OnSubspacesByCanonicalBasis errors on the zero subspace (empty list),
    # which arises when codim a equals dim A.
    safe_act_subsp := function(U, mat)
        if Length(U) = 0 then return U; fi;
        return OnSubspacesByCanonicalBasis(U, mat);
    end;
    orbits := OrbitsDomain(Mgrp, all_subs, safe_act_subsp);

    recs := [];
    for orb in orbits do
        U_rep := orb[1];
        # Lift U_rep ⊆ A to kernel K ⊆ H.
        U_gens := [];
        for v in U_rep do
            a_elem := Product(List([1..A_data.d],
                i -> A_data.pcgs[i] ^ IntFFE(v[i])));
            Add(U_gens, PreImagesRepresentative(A_data.hom, a_elem));
        od;
        K := SubgroupNC(H, Concatenation(Phi_gens, U_gens));
        stab_NH := Stabilizer(N_H, U_rep, lift_act);
        Add(recs, rec(
            K_H_gens := GeneratorsOfGroup(K),
            Stab_NH_KH_gens := GeneratorsOfGroup(stab_NH),
            # |Stab| = |N_H| / |orbit| -- free from the orbit we just enumerated;
            # avoids fresh Schreier-Sims on Stab in the labelled harvest path.
            Stab_NH_KH_size := Size(N_H) / Length(orb),
            qid := qid,
            qsize := qsize));
    od;
    return recs;
end;


# ---- Correctness scaffold ----
# Compare linear-orbit output against existing cached records for the
# same H and quotient family C_p^a.  We compare orbit count and the
# multiset of stabilizer orders; matching here is necessary but not
# sufficient for full structural agreement (a future check should
# verify that K_H representatives lie in the same N_H-orbits).
CompareWithCached := function(H, N_H, cached, p, a)
    local target_qid, cached_q, linear, sizes_c, sizes_l;
    target_qid := [p^a, 0, IdGroup(AbelianGroup(IsPcGroup, List([1..a], i -> p)))];
    cached_q := Filtered(cached,
        r -> r.qsize = p^a and r.qid = target_qid);
    linear := LinearOrbitRecsCpa(H, N_H, p, a);
    sizes_c := SortedList(List(cached_q,
        r -> Size(Group(r.Stab_NH_KH_gens))));
    sizes_l := SortedList(List(linear,
        r -> Size(Group(r.Stab_NH_KH_gens))));
    return rec(
        ok := (Length(sizes_l) = Length(sizes_c)) and (sizes_l = sizes_c),
        n_linear := Length(linear),
        n_cached := Length(cached_q),
        stab_sizes_linear := sizes_l,
        stab_sizes_cached := sizes_c);
end;


# Rich variant: returns records with hom (H -> Q) and A_gens (Aut(Q) gens
# induced by Stab_NH) precomputed via A_data's structure.  Win D1 + E1:
#   - hom is built as composition H -> A -> A/U_subgroup (cheap; A is small
#     elementary abelian) instead of NaturalHomomorphismByNormalSubgroup(H, K)
#     which would do coset enumeration in H.
#   - A_gens are derived from the precomputed N_H action matrices on A,
#     projected to A/U, instead of InducedAutoGens calling InducedAutomorphism
#     per stab gen.
LinearOrbitRecsCpaRich := function(H, N_H, p, a)
    local A_data, action, gens_NH, mats, Mgrp, V, all_subs, safe_act_subsp,
          orbits, qid, qsize, recs, Phi_gens, orb, U_rep, U_gens, v,
          a_elem, K, lift_act, stab_NH, stab_gens, g,
          U_in_A_gens, U_subgroup_in_A, hom_AU, Q_AU, pcgs_AU,
          hom_H_to_Q, M_g, j, h_j, h_j_conj, exp_vec,
          q_gen, q_gen_AU, q_gen_A, q_gen_A_exps, q_gen_A_image_exps,
          q_gen_A_image, q_gen_image, A_gens, gens_Q, q_images, g_aut;
    A_data := ElemAbPQuotient(H, p);
    if a < 1 then return []; fi;
    if a > A_data.d then return []; fi;

    qsize := p^a;
    qid := [qsize, 0, IdGroup(AbelianGroup(IsPcGroup, List([1..a], i -> p)))];
    Phi_gens := GeneratorsOfGroup(A_data.Phi);

    action := NHActionOnElemAb(N_H, A_data, p);
    mats := action.mats;
    gens_NH := GeneratorsOfGroup(N_H);

    V := GF(p) ^ A_data.d;
    all_subs := List(Subspaces(V, A_data.d - a), function(s)
        local bv;
        bv := BasisVectors(Basis(s));
        if Length(bv) = 0 then return []; fi;
        return TriangulizedMat(List(bv, ShallowCopy));
    end);

    lift_act := function(U, n)
        local M, j, a, h, nh, exp;
        if A_data.d = 0 then return U; fi;
        M := [];
        for j in [1..A_data.d] do
            a := A_data.pcgs[j];
            h := PreImagesRepresentative(A_data.hom, a);
            nh := n^-1 * h * n;
            exp := ExponentsOfPcElement(A_data.pcgs, Image(A_data.hom, nh));
            Add(M, exp * One(GF(p)));
        od;
        if Length(U) = 0 then return U; fi;
        return OnSubspacesByCanonicalBasis(U, M);
    end;

    # When A_data.d = a, the codim-a subspace is the zero subspace (an empty
    # canonical-basis list).  GAP's OnSubspacesByCanonicalBasis errors on
    # empty input (it tries mat * []), so use a wrapper that short-circuits
    # the zero-subspace case (its orbit under any matrix is itself).
    safe_act_subsp := function(U, mat)
        if Length(U) = 0 then return U; fi;
        return OnSubspacesByCanonicalBasis(U, mat);
    end;

    if Length(mats) = 0 then
        Mgrp := fail;
        orbits := List(all_subs, s -> [s]);
    else
        Mgrp := Group(mats);
        orbits := OrbitsDomain(Mgrp, all_subs, safe_act_subsp);
    fi;

    recs := [];
    for orb in orbits do
        U_rep := orb[1];
        # Build A-side subgroup spanned by U_rep + lifts to H.
        U_in_A_gens := [];
        U_gens := [];
        for v in U_rep do
            a_elem := Product(List([1..A_data.d],
                i -> A_data.pcgs[i] ^ IntFFE(v[i])));
            Add(U_in_A_gens, a_elem);
            Add(U_gens, PreImagesRepresentative(A_data.hom, a_elem));
        od;
        U_subgroup_in_A := SubgroupNC(A_data.A, U_in_A_gens);
        K := SubgroupNC(H, Concatenation(Phi_gens, U_gens));

        # Win D1: hom_H_to_Q via A composition (avoids NaturalHom on H).
        hom_AU := NaturalHomomorphismByNormalSubgroup(A_data.A, U_subgroup_in_A);
        Q_AU := Range(hom_AU);
        hom_H_to_Q := CompositionMapping(hom_AU, A_data.hom);

        if Length(mats) = 0 then
            stab_NH := N_H;
        else
            stab_NH := Stabilizer(N_H, U_rep, lift_act);
        fi;
        stab_gens := GeneratorsOfGroup(stab_NH);

        # Win E1: A_gens derived from matrix action on A, projected to Q_AU.
        # For each stab gen g, compute g's action on A as a matrix M_g (via
        # Pcgs), then evaluate on Q_AU's generators by lift -> apply -> project.
        if qsize = 1 or Length(stab_gens) = 0 then
            A_gens := [];
        else
            gens_Q := GeneratorsOfGroup(Q_AU);
            pcgs_AU := Pcgs(Q_AU);
            A_gens := [];
            for g in stab_gens do
                # M_g[i,:] = exponents of g^-1 * pcgs_A[i] * g in A.
                M_g := [];
                for j in [1..A_data.d] do
                    h_j := PreImagesRepresentative(A_data.hom, A_data.pcgs[j]);
                    h_j_conj := g^-1 * h_j * g;
                    exp_vec := ExponentsOfPcElement(A_data.pcgs,
                                                    Image(A_data.hom, h_j_conj));
                    Add(M_g, exp_vec * One(GF(p)));
                od;
                # Apply M_g to each gen of Q_AU.
                q_images := [];
                for q_gen in gens_Q do
                    q_gen_A := PreImagesRepresentative(hom_AU, q_gen);
                    q_gen_A_exps := ExponentsOfPcElement(A_data.pcgs, q_gen_A)
                                    * One(GF(p));
                    q_gen_A_image_exps := q_gen_A_exps * M_g;
                    q_gen_A_image := Product(List([1..A_data.d],
                        i -> A_data.pcgs[i] ^ IntFFE(q_gen_A_image_exps[i])));
                    Add(q_images, Image(hom_AU, q_gen_A_image));
                od;
                g_aut := GroupHomomorphismByImagesNC(Q_AU, Q_AU, gens_Q, q_images);
                SetIsBijective(g_aut, true);
                Add(A_gens, g_aut);
            od;
        fi;

        Add(recs, rec(
            K_H_gens := GeneratorsOfGroup(K),
            Stab_NH_KH_gens := stab_gens,
            # |Stab| = |N_H| / |orbit| (Stab=N_H when N_H acts trivially,
            # giving orbit length 1).  Free from already-enumerated orbit.
            Stab_NH_KH_size := Size(N_H) / Length(orb),
            qid := qid,
            qsize := qsize,
            hom := hom_H_to_Q,
            Q := Q_AU,
            A_gens := A_gens));
    od;
    return recs;
end;


Print("prototype_stage_a.g loaded.\n");
Print("  ElemAbPQuotient(H, p)\n");
Print("  NHActionOnElemAb(N_H, A_data, p)\n");
Print("  LinearOrbitRecsCpa(H, N_H, p, a)\n");
Print("  LinearOrbitRecsCpaRich(H, N_H, p, a)\n");
Print("  CompareWithCached(H, N_H, cached_orbits, p, a)\n");
