"""Scan every group in parallel_s18/[6,5,5,2]/*.g and verify that its
projection to each block of the partition [6,5,5,2] is transitive.
Purely Python — no GAP needed. A group whose projection to some block
is not transitive is a bogus FPF-subdirect (violates the surjectivity
requirement)."""
import os
import re
import collections

BASE = r"C:\Users\jeffr\Downloads\Lifting\parallel_s18\[6,5,5,2]"
BLOCKS = [list(range(1, 7)),        # [1..6]
          list(range(7, 12)),       # [7..11]
          list(range(12, 17)),      # [12..16]
          list(range(17, 19))]      # [17..18]


def parse_cycle(s):
    """Parse '(a,b,c,...)' into a tuple of ints."""
    s = s.strip()
    if s == '()' or not s.startswith('('):
        return ()
    return tuple(int(x) for x in s[1:-1].split(','))


def parse_perm(s):
    """Parse '(1,2,3)(4,5)' etc. into list of cycles (tuples of ints)."""
    cycles = []
    depth = 0
    cur = ''
    for ch in s:
        cur += ch
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
            if depth == 0:
                cyc = parse_cycle(cur)
                if cyc:
                    cycles.append(cyc)
                cur = ''
    return cycles


def perm_to_dict(cycles):
    """Turn cycle list into a dict {point: image}."""
    d = {}
    for cyc in cycles:
        for i, p in enumerate(cyc):
            d[p] = cyc[(i + 1) % len(cyc)]
    return d


def parse_group_generators(group_str):
    """Parse a group string like '[(1,2),(3,4)]' into a list of
    generator-permutations as dicts."""
    inner = group_str.strip()
    if inner.startswith('['):
        inner = inner[1:]
    if inner.endswith(']'):
        inner = inner[:-1]
    # Split at top-level commas (those not inside parentheses)
    gens = []
    depth = 0
    cur = ''
    for ch in inner:
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
        if ch == ',' and depth == 0:
            if cur.strip():
                gens.append(cur.strip())
            cur = ''
        else:
            cur += ch
    if cur.strip():
        gens.append(cur.strip())
    return [perm_to_dict(parse_perm(g)) for g in gens]


def apply_perm(perm_dict, p):
    """Apply permutation (as dict) to point p."""
    return perm_dict.get(p, p)


def is_projection_transitive(gens, block):
    """Check if the group generated by `gens` acts transitively on `block`.
    gens is a list of dicts. Orbit of block[0] under gens restricted to
    block must be all of block."""
    block_set = set(block)
    start = block[0]
    orbit = {start}
    stack = [start]
    while stack:
        x = stack.pop()
        for g in gens:
            y = apply_perm(g, x)
            if y in block_set and y not in orbit:
                orbit.add(y)
                stack.append(y)
    return orbit == block_set


def read_groups(fp):
    """Return list of (idx, group_str) for each group in file fp."""
    with open(fp, 'r') as f:
        content = f.read()
    content = re.sub(r'\\\n', '', content)
    out = []
    idx = 0
    for line in content.split('\n'):
        s = line.strip()
        if not s or s.startswith('#'):
            continue
        if s.startswith('['):
            idx += 1
            out.append((idx, s))
    return out


bogus_total = 0
files_with_bogus = 0
total_groups = 0

for fname in sorted(os.listdir(BASE)):
    if not fname.endswith('.g') or 'backup' in fname or 'Copy' in fname:
        continue
    fp = os.path.join(BASE, fname)
    bogus_in_file = []
    for idx, gs in read_groups(fp):
        total_groups += 1
        gens = parse_group_generators(gs)
        # Check each block's projection transitivity
        bad_blocks = []
        for bi, block in enumerate(BLOCKS):
            if not is_projection_transitive(gens, block):
                bad_blocks.append((bi, block))
        if bad_blocks:
            bogus_in_file.append((idx, gs, bad_blocks))
    if bogus_in_file:
        files_with_bogus += 1
        bogus_total += len(bogus_in_file)
        print(f"\n{fname}: {len(bogus_in_file)} bogus group(s)")
        for idx, gs, bad in bogus_in_file:
            bad_str = ", ".join(f"block[{b[0]}..{b[-1]}]" for _, b in bad)
            print(f"  #{idx}: non-transitive projection to {bad_str}")
            print(f"        {gs[:120]}...")

print()
print(f"Total groups scanned: {total_groups:,}")
print(f"Files with bogus groups: {files_with_bogus}")
print(f"Total bogus groups: {bogus_total}")
