LogTo("C:/Users/jeffr/Downloads/Lifting/test_centralizer_opt.log");
Read("C:/Users/jeffr/Downloads/Lifting/lifting_method_fast_v2.g");
Read("C:/Users/jeffr/Downloads/Lifting/database/lift_cache.g");
FPF_SUBDIRECT_CACHE := rec();
LIFT_CACHE := rec();
if IsBound(ClearH1Cache) then ClearH1Cache(); fi;
Print("Testing S2-S10 with centralizer optimization...\n");
startTime := Runtime();
result := CountAllConjugacyClassesFast(10);
elapsed := (Runtime() - startTime) / 1000.0;
Print("S10 = ", result, " (expected 1593), time = ", elapsed, "s\n");
if result = 1593 then Print("PASS\n"); else Print("FAIL!\n"); fi;
LogTo();
QUIT;
