LogTo("C:/Users/jeffr/Downloads/Lifting/test_quick.log");
Read("C:/Users/jeffr/Downloads/Lifting/lifting_method_fast_v2.g");
Read("C:/Users/jeffr/Downloads/Lifting/database/lift_cache.g");
FPF_SUBDIRECT_CACHE := rec();
LIFT_CACHE := rec();
if IsBound(ClearH1Cache) then ClearH1Cache(); fi;
startTime := Runtime();
result := CountAllConjugacyClassesFast(10);
elapsed := (Runtime() - startTime) / 1000.0;
Print("S10 = ", result, " (expected 1593), time = ", elapsed, "s\n");
if result = 1593 then Print("S10 PASS\n"); else Print("S10 FAIL!\n"); fi;
if IsBound(ClearH1Cache) then ClearH1Cache(); fi;
FPF_SUBDIRECT_CACHE := rec();
startTime := Runtime();
r := FindFPFClassesForPartition(12, [8,4]);
elapsed := (Runtime() - startTime) / 1000.0;
Print("[8,4] = ", Length(r), " (expected 1376), time = ", elapsed, "s\n");
if Length(r) = 1376 then Print("[8,4] PASS\n"); else Print("[8,4] FAIL!\n"); fi;
LogTo();
QUIT;
