"""Time AllHomomorphismClasses(C, A_6) for W501's actual C (size 2592).
This is the bottleneck we saw. If it takes more than ~30s, our approach
needs a smarter Hom enumeration or a fall-back."""
import subprocess, os

code = '''
LogTo("C:/Users/jeffr/Downloads/Lifting/allhom_w501.log");
Read("C:/Users/jeffr/Downloads/Lifting/lifting_method_fast_v2.g");
Read("C:/Users/jeffr/Downloads/Lifting/database/lift_cache.g");

# Reconstruct exactly as GeneralAutHomComplements would.
T1 := TransitiveGroup(6, 16);
T2 := TransitiveGroup(12, 242);
shifted := [ShiftGroup(T1, 0), ShiftGroup(T2, 6)];
offsets := [0, 6];
P := Group(Concatenation(List(shifted, GeneratorsOfGroup)));

# Get the A_6 chief factor.  Look at ChiefSeries(P).
series := ChiefSeries(P);
Print("Series sizes: ", List(series, Size), "\\n");

# The A_6 layer: find the step where Size goes from S to S/360.
layer_S := fail;
layer_N := fail;
for i in [1..Length(series)-1] do
    if Size(series[i]) / Size(series[i+1]) = 360 then
        layer_S := series[i];
        layer_N := series[i+1];
        break;
    fi;
od;
Print("Layer S: |S|=", Size(layer_S), ", |N|=", Size(layer_N), "\\n");

# At the layer, Q = S and M_bar = S/N (viewed as an internal quotient).
# For our test we want to use Q = layer_S mod layer_N.
# Actually, in the algorithm Q = S (not quotient), and we find complements
# of M_bar = layer_S-minus-N-plus-one-rep.  Simpler: Q = S, M_bar = the
# normal closure giving A_6 chief factor.
#
# But simplest of all: just compute C (centralizer) and time AllHom on it.
Q := layer_S;
# A_6 inside Q: use NormalClosure with layer_S / layer_N ...
# Actually just approximate — use A_6 = Difference generators of S / N.
# For the timing test, what matters is a C of the right size with
# realistic structure.

# C for the algorithm is Centralizer(Q, M_bar).  We approximate by
# Centralizer(Q, layer_S).  This isn\'t exactly right but gives a
# similar-structured C.
C_approx := Centralizer(Q, layer_S);
Print("C approximation: |C|=", Size(C_approx),
      ", gens=", Length(GeneratorsOfGroup(C_approx)),
      ", SGS=", Length(SmallGeneratingSet(C_approx)), "\\n\\n");

# Time AllHomomorphismClasses.
M_bar_test := AlternatingGroup(6);
Print("Timing AllHomomorphismClasses(C_approx, A_6)...\\n");
t0 := Runtime();
homs := AllHomomorphismClasses(C_approx, M_bar_test);
elapsed := Runtime() - t0;
Print("Result: ", Length(homs), " classes in ", elapsed, "ms\\n\\n");

# Also try with |C| generated by a smaller generating set.
if Length(GeneratorsOfGroup(C_approx)) <> Length(SmallGeneratingSet(C_approx)) then
    C_sm := Group(SmallGeneratingSet(C_approx));
    Print("Timing with SmallGeneratingSet-Group:\\n");
    t0 := Runtime();
    homs := AllHomomorphismClasses(C_sm, M_bar_test);
    elapsed := Runtime() - t0;
    Print("Result: ", Length(homs), " classes in ", elapsed, "ms\\n");
fi;

LogTo();
QUIT;
''';

with open(r"C:\Users\jeffr\Downloads\Lifting\tmp_allhom.g", "w") as f:
    f.write(code)

env = os.environ.copy()
env['PATH'] = r"C:\Program Files\GAP-4.15.1\runtime\bin;" + env.get('PATH', '')
env['CYGWIN'] = 'nodosfilewarning'

p = subprocess.Popen(
    [r"C:\Program Files\GAP-4.15.1\runtime\bin\bash.exe", "--login", "-c",
     'cd "/cygdrive/c/Program Files/GAP-4.15.1/runtime/opt/gap-4.15.1" && ./gap.exe -q -o 0 "/cygdrive/c/Users/jeffr/Downloads/Lifting/tmp_allhom.g"'],
    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, env=env,
    cwd=r"C:\Program Files\GAP-4.15.1\runtime",
    creationflags=subprocess.CREATE_NEW_PROCESS_GROUP)

print(f"Launched at PID {p.pid}")
print("Log: C:/Users/jeffr/Downloads/Lifting/allhom_w501.log")
