LogTo("C:/Users/jeffr/Downloads/Lifting/test_interlayer.log");
Read("C:/Users/jeffr/Downloads/Lifting/lifting_method_fast_v2.g");
Read("C:/Users/jeffr/Downloads/Lifting/database/lift_cache.g");
if IsBound(ClearH1Cache) then ClearH1Cache(); fi;
FPF_SUBDIRECT_CACHE := rec();
startTime := Runtime();
r := FindFPFClassesForPartition(12, [6,4,2]);
elapsed := (Runtime() - startTime) / 1000.0;
Print("[6,4,2] = ", Length(r), " (expected 1126), time = ", elapsed, "s\n");
if Length(r) = 1126 then Print("[6,4,2] PASS\n"); else Print("[6,4,2] FAIL!\n"); fi;
if IsBound(ClearH1Cache) then ClearH1Cache(); fi;
FPF_SUBDIRECT_CACHE := rec();
startTime := Runtime();
r := FindFPFClassesForPartition(12, [4,4,2,2]);
elapsed := (Runtime() - startTime) / 1000.0;
Print("[4,4,2,2] = ", Length(r), " (expected 2367), time = ", elapsed, "s\n");
if Length(r) = 2367 then Print("[4,4,2,2] PASS\n"); else Print("[4,4,2,2] FAIL!\n"); fi;
LogTo();
QUIT;
