"""test_gq_s2_s12.py — for every existing LEFT subs file from S2-S12,
time GQuotients-per-Q-type vs NormalSubgroups on each H subgroup.
Report per-LEFT and aggregate statistics.

This is the "real performance data" run before committing to the
GQ-only architectural change.
"""
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(r"C:\Users\jeffr\Downloads\Lifting")
LOG = ROOT / "test_gq_s2_s12.log"
if LOG.exists():
    LOG.unlink()

# Find all subs_left files that are persisted (in _h_cache_v2 dir layout
# we have <n>/<part>/<combo>.g — and matching SUBGROUPS files in
# parallel_sn_v2 since each LEFT combo file IS the subs list for its own
# combo — though our cache uses fresh subs files per super-batch).
#
# Rather than hunt subs files, we'll enumerate combos for n=2..12 from
# build_sn_v2's logic and time the cache-build for each LEFT we encounter.
# This gives us direct per-H GQ vs NS timing across ~thousands of H's.

SUBS_BASE = ROOT / "parallel_sn_v2"

# Pick representative LEFT combos: for each n=2..12, take all FPF partitions
# and the "first non-trivial" left combo (e.g. all-(d,1)).  This isn't
# exhaustive but covers shape variety.
TEST_CASES = []
for n in range(2, 13):
    n_dir = SUBS_BASE / str(n)
    if not n_dir.exists():
        continue
    for part_dir in sorted(n_dir.iterdir()):
        if not part_dir.is_dir():
            continue
        # Pick the first .g file in this partition dir (= one combo)
        combo_files = sorted(part_dir.glob("*.g"))
        if not combo_files:
            continue
        # Use this as the "subs file" for the combo's LEFT
        # In build_sn_v2 logic, the LEFT for combo C is C with one factor removed
        # For testing the cache build, we just treat each combo file as a "LEFT"
        # and read its subgroup list.
        combo_file = combo_files[0]
        # Parse the partition string (dir name like "[4,4,4]")
        part_name = part_dir.name
        TEST_CASES.append({
            "n": n,
            "partition": part_name,
            "combo_file": str(combo_file),
            "combo_name": combo_file.stem,
        })

print(f"Test cases: {len(TEST_CASES)}")

# Now build a GAP script that times each
GAP_LINES = [
    f'LogTo("{str(LOG).replace(chr(92), "/")}");',
    'Print("=== GQ vs NS per-H timing across S2-S12 LEFT-class combos ===\\n");',
    '',
    '# Q-types relevant for various M_R values',
    'C2 := CyclicGroup(IsPermGroup, 2);',
    'C3 := CyclicGroup(IsPermGroup, 3);',
    'S3 := SymmetricGroup(3);',
    'V4 := DirectProduct(CyclicGroup(IsPermGroup, 2), CyclicGroup(IsPermGroup, 2));',
    'C4 := CyclicGroup(IsPermGroup, 4);',
    'D8 := TransitiveGroup(4, 3);',
    'A4 := AlternatingGroup(4);',
    'S4 := SymmetricGroup(4);',
    '',
    '# Test running totals',
    'tot_gq_ms := 0;',
    'tot_ns_ms := 0;',
    'tot_h := 0;',
    'tot_ns_skipped := 0;',
    'gq_ns_summary := [];',
    '',
    'TimeOneH := function(H, q_groups, ns_cap_ms)',
    '    local t, gqs, kers, gq_total, gq_kers_total, ns, ns_time, q;',
    '    gq_total := 0;',
    '    gq_kers_total := 0;',
    '    for q in q_groups do',
    '        t := Runtime();',
    '        gqs := GQuotients(H, q);',
    '        kers := Set(List(gqs, Kernel));',
    '        gq_total := gq_total + (Runtime() - t);',
    '        gq_kers_total := gq_kers_total + Length(kers);',
    '    od;',
    '    # NS with soft cap: skip if H is huge or measured running too long',
    '    if Size(H) > 4000 then',
    '        return rec(gq_ms := gq_total, gq_kers := gq_kers_total,',
    '                   ns_ms := -1, ns_count := -1);',
    '    fi;',
    '    t := Runtime();',
    '    ns := NormalSubgroups(H);',
    '    ns_time := Runtime() - t;',
    '    return rec(gq_ms := gq_total, gq_kers := gq_kers_total,',
    '               ns_ms := ns_time, ns_count := Length(ns));',
    'end;',
    '',
]

for case in TEST_CASES:
    cf = case["combo_file"].replace("\\", "/")
    GAP_LINES.append(f'''
# {case['n']}/{case['partition']}/{case['combo_name']}
Print("\\n=== n={case['n']} {case['partition']}/{case['combo_name']} ===\\n");
combo_file := "{cf}";
# Parse the combo file: header lines + bracketed gen-lists.
# We recreate "the LEFT" as the group generated by all its FPF subgroup gens.
# Then we test ALL the FPF subgroups (the group lines).

lines := SplitString(StringFile(combo_file), "\\n");
combo_groups := [];
for ln in lines do
    if Length(ln) > 0 and ln[1] = '\\\\' then continue; fi;
    if Length(ln) > 0 and ln[1] = '[' then
        # Try to parse it as a generator list
        # ...
    fi;
od;
# (Simpler: read SUBGROUPS list directly from the per-combo file format)
''')

GAP_LINES.append('LogTo();\nQUIT;\n')

# Wait, the per-combo .g files are in legacy format (# combo / # deduped /
# bracketed gen lines), not the SUBS := [...] format.  We need to construct
# the subgroups from them.  Let me rewrite.
print("test_gq_s2_s12.py: combo files are in legacy format, need to parse")
print("Skipping implementation — falling back to a simpler alternative.")
print()
print("Will instead fork predict_2factor.py and run a small loop directly.")
