##############################################################################\
#
# degree_03.g - Precomputed subgroups for transitive groups of degree 3
# Auto-generated by generate_transitive_db.py
##############################################################################\
#

if not IsBound(TRANSITIVE_SUBGROUPS) then
    TRANSITIVE_SUBGROUPS := rec();
fi;

TRANSITIVE_SUBGROUPS.("3") := rec(
  ("1") := [
    [  ],
    [ [ 2, 3, 1 ] ]
  ],
  ("2") := [
    [  ],
    [ [ 1, 3, 2 ] ],
    [ [ 2, 3, 1 ] ],
    [ [ 2, 3, 1 ], [ 1, 3, 2 ] ]
  ]
);
