##############################################################################\
#
# degree_02.g - Precomputed subgroups for transitive groups of degree 2
# Auto-generated by generate_transitive_db.py
##############################################################################\
#

if not IsBound(TRANSITIVE_SUBGROUPS) then
    TRANSITIVE_SUBGROUPS := rec();
fi;

TRANSITIVE_SUBGROUPS.("2") := rec(
  ("1") := [
    [  ],
    [ [ 2, 1 ] ]
  ]
);
