H_CACHE := [ rec(
      H_gens := [ (1,2)(3,4) ],
      N_H_gens := [ (1,2), (3,4), (1,3)(2,4) ],
      computed_q_ids := fail,
      orbits := [ rec(
              K_H_gens := [  ],
              Stab_NH_KH_gens := [ (1,2), (3,4), (1,3)(2,4) ],
              qid := [ 2, 0, [ 2, 1 ] ],
              qsize := 2 ) ] ), rec(
      H_gens := [ (1,2), (3,4) ],
      N_H_gens := [ (3,4), (1,2), (1,3,2,4) ],
      computed_q_ids := fail,
      orbits := [ rec(
              K_H_gens := [ (1,2) ],
              Stab_NH_KH_gens := [ (1,2), (3,4) ],
              qid := [ 2, 0, [ 2, 1 ] ],
              qsize := 2 ), rec(
              K_H_gens := [  ],
              Stab_NH_KH_gens := [ (1,3,2,4), (1,2), (3,4) ],
              qid := [ 4, 0, [ 4, 2 ] ],
              qsize := 4 ), rec(
              K_H_gens := [ (1,2)(3,4) ],
              Stab_NH_KH_gens := [ (1,3,2,4), (1,2), (3,4) ],
              qid := [ 2, 0, [ 2, 1 ] ],
              qsize := 2 ) ] ) ];
